### ISSUE TITLE
Update Gem dependency for diff-lcs

### ISSUE THREAD

**Issue by brandonrdn** [puppetlabs/pdk#1041]
PDK requires an older version of `diff-lcs` that contains invalid shebang lines. Version 1.3 of `diff-lcs` contains ruby shebang lines `#!ruby -w` which can cause issues for systems that don't recognize the proper Ruby interpreter, and also during package builds, such as `rpmbuild` which have requirements on shebang lines. The updated versions (>= 1.4) have updated shebang lines referencing `/usr/bin/env` which solve both of these issues. Recommend bumping the `diff-lcs` gem dependency requirement from  `1.3` to `1.4` or `'>=1.4.4', '< 1.5'`.

**Comment by jpogran** [comment]
Thanks for the report. We'll investigate this for the 2.2 release
