### ISSUE TITLE
Function: pdk new module my_mdule does not work when a user name contains non-alphanumeric characters

### ISSUE THREAD

**Issue by davinhanlon** [puppetlabs/pdk#106]
My user name contains a dot (it is: davin.hanlon). When I try to create a new module using the 'pdk new module' command I get an error, as below. This is due to the presence of the dot in my username.

davin:~ davin.hanlon$ pdk new module harrumph
pdk (INFO): Creating new module: harrumph
/Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/pdk-0.2.0/lib/pdk/module/metadata.rb:101:in `validate_name': Invalid 'name' field in metadata.json: the namespace contains non-alphanumeric characters (ArgumentError)
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/pdk-0.2.0/lib/pdk/module/metadata.rb:77:in `process_name'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/pdk-0.2.0/lib/pdk/module/metadata.rb:64:in `update!'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/pdk-0.2.0/lib/pdk/module/metadata.rb:41:in `initialize'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/pdk-0.2.0/lib/pdk/generators/module.rb:35:in `new'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/pdk-0.2.0/lib/pdk/generators/module.rb:35:in `invoke'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/pdk-0.2.0/lib/pdk/cli/new/module.rb:41:in `block (2 levels) in <module:CLI>'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/cri-2.9.1/lib/cri/command.rb:319:in `run_this'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/cri-2.9.1/lib/cri/command.rb:264:in `run'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/pdk-0.2.0/lib/pdk/cli.rb:14:in `run'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/gems/pdk-0.2.0/exe/pdk:5:in `<top (required)>'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/bin/pdk:23:in `load'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/bin/pdk:23:in `<main>'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/davin.hanlon/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by DavidS** [comment]
Thanks for your report, we'll look into it! 

Apparently https://github.com/puppetlabs/pdk/blob/master/lib/pdk/generators/module.rb#L21 needs to be fixed to create a legal namespace, i.e. strip everything not matching https://github.com/puppetlabs/pdk/blob/master/lib/pdk/cli/util/option_validator.rb#L31

**Comment by scotje** [comment]
I think #103 will probably resolve this?

**Comment by DavidS** [comment]
@scotje nope, the validation fails during initialisation, way before anything #103 touches. I've added a simple test to #108, we can continue there.

**Comment by DavidS** [comment]
This was fixed by #108
