### ISSUE TITLE
pdk build: It is not possible to create a pkg dir due to permissions 

### ISSUE THREAD

**Issue by pmcmaw** [puppetlabs/pdk#1075]
**Describe the bug**
Currently when using the pdk build command and directories having all permissions it fails to create the directory and throws the following error: 

```
pdk (INFO): Building puppetlabs-iis version 8.0.1
--
6/opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/fileutils.rb:230:in `mkdir': Permission denied @ dir_s_mkdir - /github/workspace/pkg (Errno::EACCES)
7	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/fileutils.rb:230:in `fu_mkdir'
8	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/fileutils.rb:208:in `block (2 levels) in mkdir_p'
9

```
Note the error only happens on the nightly build. When pinning back to v2.1.0.0 this all works fine. 

**To Reproduce**
Currently when using any of the Supported Modules 'Release to Forge' workflow the error is thrown. Note that when running this locally, there is no issue. 

**Expected behavior**
I expect the module to be built and and released to the Forge. 

**Additional context**
- This is a link to a build using pdk nightly, you can see folder permissions etc means it should have access to write but fails:  https://github.com/pmcmaw/puppetlabs-iis/actions/runs/785879334

- This is a link to a build using the latest tagged build 2.1.0.0: https://github.com/pmcmaw/puppetlabs-iis/actions/runs/785891904

**Comment by da-ar** [comment]
This issue should be resolved when  puppetlabs/pdk-docker#31 is merged

**Comment by da-ar** [comment]
@pmcmaw would you be able to confirm that this issue is resolved for you?

**Comment by pmcmaw** [comment]
@da-ar I can confirm this issue has been resolved.
Thank you very much for this. 

Link to passing job: https://github.com/carabasdaniel/puppetlabs-iis/runs/2599177966?check_suite_focus=true

Going to close with this comment.

**Comment by pmcmaw** [comment]
![Uploading Screen Shot 2021-05-17 at 9.58.30 AM.png…]()
