### ISSUE TITLE
PDK validate missing warnings

### ISSUE THREAD

**Issue by rogermartensson** [puppetlabs/pdk#1076]
**Describe the bug**
When refactoring some manifests in a module of mine I noticed that I was missing some warnings in VSCode. I noticed the same problem when running "pdk validate" on the command line.

I was expecting to see many "top-scope variable being used without an explicit namespace" frompuppe-lint during me working with the files but I did not see any such messages.

**To Reproduce**
I noticed this when I was using "non-ascii" characters when using fail().

My original message contained an ä-character but I could reproduce it with an ½-character in my environment. Both is above 127 and that the reason I say "non-ascii".

Example: fail("½")

A workaround is to use this:
$str="½"
fail($str)

(I hope you will be able to reproduce)

**Expected behavior**
The missing warning messages should be visible using "pdk validate"

**Additional context**
- Your PDK installation method: Windows install package
- Your PDK version: 2.1.0
- Your operating system / platform; Windows 10

**Comment by jpogran** [comment]
Thanks for the report! We'll have to determine if this is a bug or a new feature to implement in puppet-lint. Once that's done we'll create an issue in the puppet-lint repo to surface this

**Comment by sanfrancrisko** [comment]
Thanks @rogermartensson - I'm struggling to reproduce this issue. Would you be able to provide a snippet of the manifest where you're seeing this issue?

**Comment by rogermartensson** [comment]
Here is some simple test code that I can use to toggle the warning on and off.
```puppet
#
class a::t {
  if $x == 1 {
      fail("½ ${x}")
      notify { "${x}": }
  }
}
```

By removing the ½-character the warning is shown inside the Problem Tab in VSCode but I can also see the same message when running `pdk validate`. The warning disappears when I insert the ½-character again.

With the notify you also get another warning. "string containing only a variable"
That warning never disappears.  So by commenting/uncommenting the row with fail() you can toggle from 1 warning to three warnings.

**Comment by sanfrancrisko** [comment]
Thanks for providing that code snippet and the explanation @rogermartensson  - I can see this issue now. I suspect the linter within `puppet-lint` is being thrown off (I can reproduce this issue by directly invoking `puppet-lint`). I'll raise the issue there and link to this issue, as this is where the problem appears to be.

Thanks again for reporting!
