### ISSUE TITLE
Ensure latest puppet, ruby 2.7 and rspec-puppet

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdk#1087]
There have been several performance improvements in the latest puppet and ruby distributions. We need to make sure these come out in the next release.

We need to verify that the latest release of rspec-puppet is also included

Investigate the puppet-runtime auto update process

**Comment by da-ar** [comment]
It looks like debian 8 was removed from the puppet-runtime vanagon build. This then failed the usual promotion to pdk-vanagon due to the pdk-runtime trying to build debian 8.
