### ISSUE TITLE
Puppet 5 / Ruby 2.4 Continued Support

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/pdk#1099]

**Comment by sanfrancrisko** [comment]
- Determine what PE LTS's current supported versions of Puppet are:
  - https://puppet.com/docs/puppet-enterprise/product-support-lifecycle/
  - https://puppet.com/docs/pe/2021.1/component_versions_in_recent_pe_releases.html 
- Determine the next LTS release's intended support for Puppet versions is and estimated release date
- Conversation with PM to determine what level of Puppet 5 support we're on the hook for:
  - Can we go with the line that if you require Puppet 5 support you use an older PDK version?

**Comment by jpogran** [comment]
Puppet 5 and Ruby 24 will continue to be shipped in the PDK 2.X timeline
