### ISSUE TITLE
Investigate configuration options for pdk validate

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdk#1111]
Investigate how to solve https://github.com/puppetlabs/pdk/discussions/1066

**Comment by DavidS** [comment]
Example for one specific, limited solution: https://github.com/puppetlabs/puppetlabs-peadm/blob/596309a0439f2c5ad9efc1385fd1bd46f3214634/.sync.yml#L18

**Comment by DavidS** [comment]
It turns out that that doesn't work for `pdk validate` because https://github.com/puppetlabs/pdk/blob/dca0eb783de78d11007b07d7734ebe95f4597447/lib/pdk/validate/puppet/puppet_syntax_validator.rb#L53 doesn't call the rake task.

**Comment by jpogran** [comment]
So, as #1066 implies and @DavidS recent comments imply, this is a complicated interplay of tools and settings. For the purposes of this ticket, we are focusing on validators for json, yaml, puppet (executed within pdk's ruby process) and not external validators like rubocop (executed out of process). Each of these validators set a [pattern to pull](https://github.com/puppetlabs/pdk/blob/main/lib/pdk/validate/yaml/yaml_syntax_validator.rb#L17-L33) target files in and a [pattern to ignore](https://github.com/puppetlabs/pdk/blob/main/lib/pdk/validate/puppet/puppet_syntax_validator.rb#L39-L41) certain files. These are hardcoded and not available for user choice, so there isn't a current way to enable configuring these.

As a result of this investigation, I found we can enable a user to add to these allow/ignore patterns by modifying https://github.com/puppetlabs/pdk/blob/main/lib/pdk/validate/invokable_validator.rb#L197-L217 to accept an array of file names or patterns. There already is functionality to set configuration using `pdk set config`. If we add a new configuration setting for files to ignore when validating, we can have this method pick up those entries and all validators will be able to use this list.

This set of configuration is project scoped, as there really isn't a use case for having a global set of files to ignore. Files like this are project specific so using a config file that is committed along with the source code makes sense. The PDK config system already has a concept of project level config, but unfortunately never made the decision on file name and type.

Ticket #1117 will address picking the name and type of the project config file to use. Then #1118 will add the required code to read that file and add the patterns to ignore.

**Comment by jpogran** [comment]
Closing this as investigation is complete. Any further comments or investigation will be done in the linked tickets
