### ISSUE TITLE
Add support for SLES 15

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/pdk#1119]
As a result of #1112, SLES 15 was deemed to be more effort than a "quick win" that would involve extra work. There appears to be build dependency installation issues that need to be resolved for the build and test targets in Vanagon before we can add support for SLES 15:

```sh
11:03:01 'pl-gcc' not found in package names. Trying capabilities.
11:03:01 No provider of 'pl-gcc' found.
11:03:01 An error was encountered evaluating block. Retrying..
11:03:01 Block failed maximum number of 1 tries
11:03:01  with error Remote ssh command (zypper -n --no-gpg-checks install -y cmake pkgconfig zlib-devel pl-gcc ) failed on 'root@fussy-warehouse.delivery.puppetlabs.net'.
```

**Comment by tuxmea** [comment]
Are there any plans to provide PDK for SLES 15 within a reasonable time?
Customers are upgrading from SLES 12 to 15 and have urgent need for PDK on SLES15.

**Comment by tuxmea** [comment]
Are there any updates on this issue?

**Comment by martux69** [comment]
Are there any news about it? There are ongoing difficults in using the sles12 packages with sles15 installation ....

**Comment by tuxmea** [comment]
Can someone please put this on the backlog? Many customers want to upgrade (or already have upgraded) an can no longer use PDK.

**Comment by chelnak** [comment]
SLES 15 should be supported as of v2.5.0.

Let us know if there are any issues.

**Comment by tuxmea** [comment]
I can not see SLES15 download on 
- the PDK website: https://puppet.com/try-puppet/puppet-development-kit/
- the PDK documentation website https://puppet.com/docs/pdk/2.x/pdk_install.html

The package is listed on the yum.puppet.com repo: https://yum.puppet.com/puppet-tools/sles/15/x86_64/index.html

Can someone please add the SLES15 information to the mentioned websites?

**Comment by chelnak** [comment]
Ok interesting. I'll take a look on Tuesday with @pmcmaw . It should be an easy fix.

**Comment by chelnak** [comment]
SLES15 support should now be resolved
