### ISSUE TITLE
Make `pdk test unit --format=junit:report.xml --verbose` both show rspec documentation and generate junit file

### ISSUE THREAD

**Issue by JohnEricson** [puppetlabs/pdk#1123]
### Discussed in https://github.com/puppetlabs/pdk/discussions/1122

<div type='discussions-op-text'>

<sup>Originally posted by **JohnEricson** July  7, 2021</sup>
PDK version: 2.1.1
OS: Windows

I have a Jenkins job that runs `pdk test unit --format=junit:report.xml` on all of my modules. Now I would also like the job to show the rspec documentation format by adding the `--verbose` option to pdk. This to make it easier for people to see the status/documentation of all the tests in the module.
But `--verbose` doesn't show anything when used together with `--format=junit:report.xml`. But it works fine when used with `--format=..` like this `pdk test unit --verbose`.
I would like pdk to be improved so both of these options work together.</div>

**Comment by sanfrancrisko** [comment]
For visibility, response added [here](https://github.com/puppetlabs/pdkgo/discussions/189#discussioncomment-1357371)

**Comment by coreymbe** [comment]
@chelnak :: Are we able to close this issue?

**Comment by chelnak** [comment]
Yes sir! The feature will be included in the upcoming 3.0 release.

**Comment by JohnEricson** [comment]
Good job guys! 👍
