### ISSUE TITLE
`pdk new module` doesn't pass `pdk validate`

### ISSUE THREAD

**Issue by awrenn** [puppetlabs/pdk#1129]
**Describe the bug**
Running `pdk new module` should create a module that matches the most up-to-date style.

**To Reproduce**
Run `pdk new module`, and follow the steps. Then, run `pdk validate` inside this module. Then `echo $?` to see that `pdk validate` returned an error.

**Expected behavior**
The puppet code that `pdk new module` generates should exit with status code 0.

**Additional context**
PDK 2.1.1, installed via Ubuntu

Current errors I see are rubocop warnings only:
```
pdk (CONVENTION): rubocop: `include` is used at the top level. Use inside `class` or `module`. (spec/spec_helper.rb:12:1)
pdk (CONVENTION): rubocop: Avoid comma after the last item of a hash. (spec/spec_helper.rb:16:32)
pdk (CONVENTION): rubocop: Avoid comma after the last item of an array. (spec/spec_helper.rb:21:82)
pdk (CONVENTION): rubocop: Avoid rescuing without specifying an error class. (spec/spec_helper.rb:29:3)
pdk (CONVENTION): rubocop: Use `//` around regular expression. (spec/spec_helper.rb:53:5)
pdk (CONVENTION): rubocop: Use `//` around regular expression. (spec/spec_helper.rb:54:5)
pdk (CONVENTION): rubocop: Avoid comma after the last item of an array. (spec/spec_helper.rb:54:13)
```

**Comment by sanfrancrisko** [comment]
Thanks for reporting @awrenn - I'm not able to reproduce this locally. Could I confirm what version of the templates you're using by running `tail -n 4 metadata.json` in your module root?

```sh
tail -n 4 metadata.json 
  "pdk-version": "2.1.1",
  "template-url": "pdk-default#2.1.1",
  "template-ref": "tags/2.1.1-0-g03daa92"
}
```

**Comment by da-ar** [comment]
Closing stale ticket. If this is still an issue please feel free to reopen with additional information.
