### ISSUE TITLE
Acceptance tests on Windows using Github Actions Workflow

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/pdk#1135]
### Discussed in https://github.com/puppetlabs/pdk/discussions/1037

<div type='discussions-op-text'>

<sup>Originally posted by **sanfrancrisko** March 24, 2021</sup>
In the continuing effort (see #GH-958) to remove the dependencies on Travis and AppVeyor, we should have acceptance tests running on Github Actions.

For Windows, the IAC Team's [provision service](https://github.com/puppetlabs/provision_service) can be used to spin up a Windows Server 2019 and 2016 host with the following Ruby versions:

- `2.5`
- `2.7`

## Acceptance Criteria

- [ ] Provisions a `windows-2019` runner on Github
- [ ] Sets up Ruby 2.5 on this Windows Server 2019 host
- [ ] Executes the `acceptance:local_parallel` Rake task
- [ ] Will execute against Ruby `2.5` on this Windows 2019 host
- [ ] Provisions a `windows-2016` runner on Github
- [ ] Sets up Ruby 2.5 on a Windows Server 2016 host
- [ ] Executes the `acceptance:local_parallel` Rake task
- [ ] Will execute against Ruby `2.5` on a Windows 2016 host

- [ ] Provisions a `windows-2019` runner on Github
- [ ] Sets up Ruby 2.7 on this Windows Server 2019 host
- [ ] Executes the `acceptance:local_parallel` Rake task
- [ ] Will execute against Ruby `2.7` on this Windows 2019 host
- [ ] Provisions a `windows-2016` runner on Github
- [ ] Sets up Ruby 2.7 on a Windows Server 2016 host
- [ ] Executes the `acceptance:local_parallel` Rake task
- [ ] Will execute against Ruby `2.7` on a Windows 2016 host</div>

**Comment by pmcmaw** [comment]
This is completed and acceptance tests are running on Github Workflows for Windows.
