### ISSUE TITLE
How do I build from a parent folder containing multiple moduels ?

### ISSUE THREAD

**Issue by nlmlhc-root** [puppetlabs/pdk#1145]
Needless to say, the the move from puppet to pdk totally ruined my older long-working setup )

I have a CI/CD pipeline and about 50 modules to build at one, how can I build all of them at once ?

**Comment by da-ar** [comment]
I'd suggest using a shell script loop over each directory and call `pdk build` on each loop. This isn't functionality that the PDK supports or will directly.
