### ISSUE TITLE
Provide SRPM or RPM SPEC file for PDK

### ISSUE THREAD

**Issue by sreerajkksd** [puppetlabs/pdk#1146]
We would like to make some minor tweaks to pdk to work within our environment, but I couldn't find the source RPM packages or RPM SPEC file for pdk anywhere. 

Where do we manage the SRPMs for PDK? if we can't provide SRPM, if I can get the rpm spec file, that would help.

Thanks for the help!

**Comment by sanfrancrisko** [comment]
Hi @sreerajkksd ,

Unfortunately the build and packaging of the RPMs is performed by our company wide build platform, internally. These are not accessible and the build process does not retain the SRPMs when it is complete.

**Comment by sreerajkksd** [comment]
What about the RPM SPEC file ?

**Comment by sanfrancrisko** [comment]
Actually yes, this is available in ERB template format [here](https://github.com/puppetlabs/vanagon/blob/main/resources/rpm/project.spec.erb), if that's of use.
