### ISSUE TITLE
PDK not available on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by baron1405** [puppetlabs/pdk#1182]
**Describe the bug**
There is no release of the PDK on Ubuntu 22.04.

**To Reproduce**
Attempt to install PDK on Ubuntu 22.04.

**Expected behavior**
Ubuntu 22.04 has been out for over four months so I expected a release of the PDK for 22.04 would be available by now.

**Comment by baron1405** [comment]
Given the blocking nature of this bug, could you please triage this issue.

**Comment by Enucatl** [comment]
I installed the package from ubuntu 20.04 and it works.

**Comment by abegosum** [comment]
I am running into this issue as well, and have reported it over on the JIRA for the puppet repository with no response for a while now.

**Comment by baron1405** [comment]
@abegosum Can you provide the link for the JIRA so I can up vote and follow it. Thanks!

**Comment by abegosum** [comment]
@baron1405 Here's the JIRA ticket: https://tickets.puppetlabs.com/browse/PDK-1796

**Comment by baron1405** [comment]
@abegosum Thanks, I have upvoted the issue.

**Comment by abegosum** [comment]
For anyone else who, like me, is kinda stuck:  If you have puppet-agent installed on your Ubuntu box, you can install `pdk` into the Puppet gems.

```
# /opt/puppetlabs/puppet/bin/gem install pdk
```

It's not as pretty, but if the puppet command is already on your path via the agent install, this should work until they get this sorted.

**Comment by baron1405** [comment]
Five months and this issue has not been triaged. There is still no official version of the PDK for the latest Ubuntu LTS. Has the PDK been abandoned?

**Comment by abegosum** [comment]
For anyone else who'd been looking on this issue, looks like they have pdk for Jammy finally.

```
$ apt info pdk
Package: pdk
Version: 2.6.1.0-1jammy
Priority: optional
Section: admin
Maintainer: Puppet, Inc. <info@puppet.com>
Installed-Size: 866 MB
Homepage: https://www.puppet.com
Download-Size: 349 MB
APT-Sources: http://apt.puppetlabs.com jammy/puppet6 amd64 Packages
Description: Puppet Development Kit
 .
 Contains the following components:
 gem-prune
 pdk-create-ruby-tarballs
 pdk-runtime 202301231
 pdk-templates unknown
 puppet-specifications 4.6.0-267-gd2e1fcd
 puppet-versions
 rubygem-addressable 2.5.2
 rubygem-bundler 2.1.4
 rubygem-childprocess 4.0.0
 rubygem-colored 1.2
 rubygem-concurrent-ruby 1.1.5
 rubygem-cri 2.10.1
 rubygem-deep_merge 1.2.1
 rubygem-diff-lcs 1.4.4
 rubygem-equatable 0.6.1
 rubygem-facter 2.5.1
 rubygem-hitimes 2.0.0
 rubygem-hitimes 2.0.0
 rubygem-httpclient 2.8.3
 rubygem-json-schema 2.8.0
 rubygem-json_pure 2.1.0
 rubygem-json_pure_r27 2.5.1
 rubygem-minitar 0.6.1
 rubygem-necromancer 0.5.0
 rubygem-pastel 0.8.0
 rubygem-pathspec 0.2.1
 rubygem-pdk 2.6.1
 rubygem-public_suffix 3.0.0
 rubygem-tty-color 0.5.1
 rubygem-tty-cursor 0.7.1
 rubygem-tty-prompt 0.22.0
 rubygem-tty-reader 0.8.0
 rubygem-tty-screen 0.8.1
 rubygem-tty-spinner 0.9.1
 rubygem-tty-which 0.4.1
 rubygem-wisper 2.0.0
 shellpath
```

**Comment by baron1405** [comment]
Thanks @abegosum for pointing this out. Indeed, the [PDK 2.6.1](https://www.puppet.com/docs/pdk/2.x/release_notes_pdk.html#pdk-261) release notes state that Ubuntu 22.04 is now supported. Note that they have not updated the [Installing Pdk](https://www.puppet.com/docs/pdk/2.x/pdk_install.html) page but that is probably an oversight. I am going to close this with thanks to all those who participated.

**Comment by chelnak** [comment]
Good spot @baron1405 .

I can get this actioned.

**Comment by baron1405** [comment]
@chelnak No worries and thanks for attending to the install page!
