### ISSUE TITLE
pdk validate returning puppet-lint: invalid option

### ISSUE THREAD

**Issue by rychannel** [puppetlabs/pdk#1186]
I get the following error when running PDK if I have --no-manifest_whitespace_opening_brace_after-check specified in my Puppet-lint.rc

puppet-lint: invalid option: --no-manifest_whitespace_opening_brace_after-check
puppet-lint: try 'puppet-lint --help' for more information

**Comment by david22swan** [comment]
@rychannel I was unable to reproduce this, after adding the specified check to my local `.puppet-lint.rc` and investigation into the puppet-lint commands shows it clearly.
From what I can tel this may have been a compatibility issue, where the puppet-lint version bundled with the pdk version you were using did not yet posses this check, an issue which seems to be resolved.
As such I plan to close this issue, if I am wrong and this is still an issue that you are dealing with please feel free to re-open it and ping me to take another look.
