### ISSUE TITLE
Download links for macOS 10.13 and 10.14 are broken

### ISSUE THREAD

**Issue by claviola** [puppetlabs/pdk#1202]
From the [PDK download](https://www.puppet.com/downloads/puppet-development-kit) page:

https://pm.puppet.com/cgi-bin/pdk_download.cgi?dist=osx&rel=10.13&arch=x86_64&ver=latest
https://pm.puppet.com/cgi-bin/pdk_download.cgi?dist=osx&rel=10.14&arch=x86_64&ver=latest

Both 404.

**Comment by chelnak** [comment]
Thanks for this! We will look in to it.

**Comment by claviola** [comment]
@chelnak thanks! while I'm at it :) can we get an arm64 build for macOS 12/13?

**Comment by chelnak** [comment]
Good morning! 

The downloads page should now reflect the packages for PDK that are published.

There are no arm builds planned yet but it is something that is on our radar.
