### ISSUE TITLE
Executable files in a PDK template do not end up as executable in the module

### ISSUE THREAD

**Issue by chelnak** [puppetlabs/pdk#1224]
Issue moved from [PDK-1803](https://tickets.puppetlabs.com/browse/PDK-1803)

## The Problem

I have a PDK template where the moduleroot/ has a folder with scripts that are marked executable.

```
~/src/pdk-template$  ls -l moduleroot/ci_scripts
total 8
-rwxr-xr-x@ 1 nate  nate  287 Mar 10 15:34 validate_things.sh
```

When I build a module based on this PDK template, the validate_things.sh script does not get created as executable. Also when updating a module based on this template, the script remains not executable.

## What is expected

A file that's executable in a PDK template (either in moduleroot or moduleroot_init) should be created/updated by the PDK as executable in the module.

## What actually happens

Executable files are created without the execute bit set, making them non-executable.
This also happens when pdk update'ing a module.

**Comment by natemccurdy** [comment]
# Reproduction

Here’s a reproduction case. It’s a new PDK module based on a fork of PDK templates that includes an executable file:
* https://github.com/natemccurdy/pdk-templates/blob/PDK-1803/reproduction/moduleroot/validate_things.sh

 
```
~ $ pdk new module --template-url=https://github.com/natemccurdy/pdk-templates --template-ref=PDK-1803/reproduction

...(snip interview dialog)...

~ $ cd test                                     
~/test $ ls -l validate_things.sh               
.rw-r--r-- 218 nate 15 Mar 13:50 validate_things.sh

~/src/test $ bash validate_things.sh
validate_things.sh is NOT executable
```

**Comment by ghoneycutt** [comment]
+1 on fixing this as it makes development harder since templated scripts cannot just be executed locally and work arounds for CI/CD have to be put in place.

**Comment by chelnak** [comment]
Hey! With tasks in the pipeline for puppet 8 readiness I don't think I'll personally have time to work on this.

However! This is open source! So if anyone wants to contribute towards this feature I'm happy to assist.

My only concern here is shipping around executable files could be seen as a security risk by some.. so we would need to cover that.

**Comment by jordanbreen28** [comment]
see 
https://github.com/puppetlabs/pdk/pull/1289
 Merged
https://github.com/puppetlabs/pdk-templates/pull/539
