### ISSUE TITLE
PDK RPM for EL7 not relocatable

### ISSUE THREAD

**Issue by jjperry69** [puppetlabs/pdk#189]
I noticed when trying to install via RPM on a RHEL 7.3 server as my local account, it bombed on not having access to install, as would be expected. When I tried to --prefix=<homedir> it told me it was not relocatable. 

The gem version had no issues installing in my Dev environment in my local account. 

Not a big issue, but something to consider on the RPM builds for developers that don't have Vagrant access and are installing in their home directories.

**Comment by james-stocks** [comment]
Thanks for the suggestion - I created an internal work ticket https://tickets.puppetlabs.com/browse/PDK-445 for this to be reviewed

**Comment by jjperry69** [comment]
Great. Trying to help give back where ok can.

**Comment by sanfrancrisko** [comment]
Going to close this issue due to the age and after testing that I can install ver 2.0 of the PDK on an EL7 via the native package manager. Feel free to ping back if you still have issues @jjperry69 . 

Thanks for raising the issue!
