### ISSUE TITLE
Add /bin/ to .gitignore

### ISSUE THREAD

**Issue by Cinderhaze** [puppetlabs/pdk#208]
When following the steps in the readme, after generating the module I ran a `git init && git add . && git commit -m "Initial commit"`.  I then ran a `pdk validate` from the module directory, and noticed that it created a `/bin/` directory.  Should that be added to the generated .gitignore file?

**Comment by DavidS** [comment]
I put up https://github.com/puppetlabs/pdk-module-template/pull/22 to fix this.
