### ISSUE TITLE
Running PDK behind a corporate proxy fails

### ISSUE THREAD

**Issue by JustRiedy** [puppetlabs/pdk#227]
Environment:
- NTLM Auth based Proxy
- Windows 7
- Powershell v5
- PDK v0.5.0.0 (Installed using provided .msi package)

Currently PDK fails to function behind a corporate proxy.
![000562](https://user-images.githubusercontent.com/14937219/29057298-f114264c-7c3b-11e7-96ef-9b529b25584c.png)

I could find no documentation on this issue, but after some experimenting I found setting the following environment variables in Powershell before running PDK commands allows it to communicate.

`
$env:http_proxy="http://user:password@proxy.domain.com:port"
$env:HTTP_PROXY="http://user:password@proxy.domain.com:port"
$env:https_proxy="http://user:password@proxy.domain.com:port"
$env:HTTPS_PROXY="http://user:password@proxy.domain.com:port"
`

**Comment by DavidS** [comment]
Thank you for your report! I'm glad you found a solution.

I'm wondering if the all caps versions are really needed - from the resources I found, only the lower-case ones are required. Would you mind checking that?

We're tracking that internally at https://tickets.puppetlabs.com/browse/PDK-393

**Comment by JustRiedy** [comment]
I completed some further testing and it works fine with either Upper or Lower case only.

So lower case only is fine.
`
$env:http_proxy="http://user:password@proxy.domain.com:port"
$env:https_proxy="http://user:password@proxy.domain.com:port"
`

**Comment by bmjen** [comment]
This was addressed in PDK Documentation. Found here: https://puppet.com/docs/pdk/1.x/pdk_install.html#ariaid-title10
