### ISSUE TITLE
Support for fedora

### ISSUE THREAD

**Issue by witjoh** [puppetlabs/pdk#234]
Any plans in building RPM's for fedora ?

**Comment by scotje** [comment]
We plan to re-evaluate the platforms/distros that we build packages for after the 1.0 release. I would personally say that Fedora and Debian packages are the next highest priority for inclusion.

I've created a ticket in JIRA to track this as well: https://tickets.puppetlabs.com/browse/PDK-399

Thanks for the feedback!

**Comment by ardrigh** [comment]
@scotje was there any progress on supporting PDK on Fedora?

I use Fedora for my work laptop to deploy on EL hosts. It would be nice to have a native package for development (create modules, create tests) and running tests before I push upstream.

At the moment I spin up an CentOS VM to install new PDK versions and try out new things. But that's not a great workflow without many of my main user apps.

**Comment by ardrigh** [comment]
Just to bring this topic up again. 

I see there is a package available for [Puppet Agent 5.5.0 for Fedora 27](https://yum.puppet.com/puppet5/fedora/27/).

These AIO packages contain everything except the kitchen sink... and the PDK. Is there any chance PDK can be added to these builds scripts?

**Comment by ardrigh** [comment]
I have added a comment into https://tickets.puppetlabs.com/browse/PDK-974 regarding the recent 
Fedora 28 release.

Thanks for working on these Fedora packages :+1:

**Comment by rodjek** [comment]
Thanks @ardrigh! As of PDK 1.6.0, we're now shipping Fedora 26 and 27 RPMs in the yum.puppet.com repositories. I've opened https://tickets.puppetlabs.com/browse/PDK-1050 to track the development of Fedora 28 packages.

**Comment by ardrigh** [comment]
Thanks! 

I have installed the Puppet5 release package http://yum.puppet.com/puppet5/puppet5-release-fedora-27.noarch.rpm 

And `sudo dnf install pdk` works :beers:

**Comment by ardrigh** [comment]
With Fedora moving to make their modular repositories standard going forward, it would be interesting to see if Puppet & PDK will take advantage of this.

Allowing for future streams `puppet:5` and `puppet:6` for example :)

https://docs.fedoraproject.org/fedora-project/subprojects/fesco/en-US/making-modules/adding-new-modules.html

**Comment by scotje** [comment]
Going to go ahead and close this issue now, feel free to follow the above linked JIRA ticket for updates about Fedora 28.
