### ISSUE TITLE
Conflicting EOL character configuration

### ISSUE THREAD

**Issue by JustRiedy** [puppetlabs/pdk#267]
Environment:
* PDK Version 1.0.1

Issue:
When generating a module via pdk it creates a .gitattributes with the following contents.

> *.rb eol=lf 
*.erb eol=lf 
*.pp eol=lf 
*.sh eol=lf 

But when attempting to use the inbuilt validation on a repo thats been pushed through git atleast once
`pdk validate ruby -a`
it fails complaining the Carriage Return is missing as the files have been made LF instead of CRLF.

> PS C:\cygwin64\git\Puppet4Work\pdktest> pdk validate ruby -a
[X] Checking Ruby code style (**/**.rb)
convention: rubocop: spec/spec_helper.rb:1:1: Carriage return character missing.

Is it possible to modify the validation to prefer LF instead?

**Comment by james-stocks** [comment]
Hi Justin -

Thanks for the bug report.
I've added this to our internal issue tracker: https://tickets.puppetlabs.com/browse/PDK-443

This Github issue can remain open while we process that JIRA ticket

Thanks!

**Comment by ragnarkon** [comment]
Internal issue tracker already lists a solution.  But for those who opted to take difficult route and not read the ticket (like myself)... here is the solution:

Add the following to the `.rubocop.yaml` file:
```yaml
Style/EndOfLine:
  EnforcedStyle: lf
```

**Comment by rodjek** [comment]
Thanks, the fix for this has been merged into https://github.com/puppetlabs/pdk-module-template

**Comment by glennsarti** [comment]
@rodjek This can have one side effect.  If you have a Windows Batch file it expects CRLF.  Does rubocop enforce on ERB/EPP files?

This also implies that all ruby files should be LF. IIRC There is no technical limitation and Puppet/Ruby will quite happily parse files with CRLF line endings.  Are you sure you want to add this limitation?  if so, This should be documented in the PDK and CRLF is not "allowed".

**Comment by glennsarti** [comment]
IMO, Enforced style should be Disabled, not strictly LF
