### ISSUE TITLE
Default Gemfile for new module need linting

### ISSUE THREAD

**Issue by alvagante** [puppetlabs/pdk#273]
The Gemfile which is created by default on a new module has some style issues that could be fixed.

This is the code quality review from Codacy, on the Gemfile or our control-repo which has been copied from PDK module skeleton:

https://www.codacy.com/app/example42/psick/file/9408172385/issues/source?bid=5179524&fileBranchId=5179524

If you are interested in a PR which addresses those issues, I can prepare one.

**Comment by alvagante** [comment]
FYI, those warning are based on Rubocop checks

**Comment by DavidS** [comment]
Comparing the file you linked to, to the current template (e.g. https://github.com/puppetlabs/pdk-module-template/blob/5db7961352cda998578e3abf811b35604abb1505/moduleroot/Gemfile.erb#L45) there seems to be something weird going on. If you have installed from the native package, you should have a local cache of the template in `/opt/puppetlabs/pdk/share/cache/pdk-module-template.git`, and `git describe --all --long` should read

```
heads/master-0-g5db7961
```

**Comment by alvagante** [comment]
Yes, I have that version.
Note that compared to the one generated by pdk new module I have added a few gems:
```
0a1,3
> # Based on pdk default Gemfile
> # Added danger gems
>
125a129,134
>
> # Danger integration: http://danger.systems
> gem 'danger'
> gem 'danger-changelog'
> gem 'danger-mention'
>
```
but most of the contents are the same

**Comment by DavidS** [comment]
I'm confused. The link in the original report showed a Gemfile that was clearly not from the pdk-module-template. Now it seems to have changed to match the template, and there are no issues reported on that page.

**Comment by alvagante** [comment]
Ugh  I was a bit confused too.
GIve a look here:
https://gist.github.com/alvagante/94984de1e663f3eac29d8656221dfefb
then I realised I were seeing a lot more warnings on my version becuase I had nit custom .rubocop.yml locally. Sorry for bothering.
