### ISSUE TITLE
Write .fixtures.yml based on metadata.json

### ISSUE THREAD

**Issue by waveclaw** [puppetlabs/pdk#283]
Testing PDK 1.0.0 on MacOS X 10.12.6 creates a module structure that lacks a /.fixtures.yml file.

When running `pdk test unit` there are no dependency fixtures deployed because of this.  

Only the link back to the module in `/spec/fixtures/modules/<name of module>` is written when `pdk test unit` is run.

If a /.fixtures.yml file is manually written it will be honored.

The tool could write a /.fixtures.yml file based on /metadata.json or at least deploy with a basic commented-out version that suggests the common tasks.  

Common tasks include adding a forge dependency,  GitHub or GitLab repository and linking to existing local modules.

**Comment by DavidS** [comment]
Hi, thanks for your feedback! I've created https://github.com/puppetlabs/pdk-module-template/pull/36 to address this.
