### ISSUE TITLE
New release of tty-spinner

### ISSUE THREAD

**Issue by piotrmurach** [puppetlabs/pdk#291]
Hey, 

I had received some awesome contributions from @austb and wanted to let you know that I've released new version `v0.7.0` of tty-spinner. The most important change regards display order of registered spinners [read more](https://github.com/piotrmurach/tty-spinner/issues/25). Also, you don't have to start top level spinner anymore as it is automatically started when any registered child spinners start spinning. Hope it helps.

**Comment by bmjen** [comment]
Thanks @piotrmurach ! We will check it out!

**Comment by bmjen** [comment]
This effort will be tracked in JIRA by: https://tickets.puppetlabs.com/browse/PDK-871

**Comment by sanfrancrisko** [comment]
This was implemented in PDK 1.13.0
