### ISSUE TITLE
Wrong URL in module interview

### ISSUE THREAD

**Issue by farkasmate** [puppetlabs/pdk#302]
In the license step of the interview the hint is pointing at the wrong URL.

### Expected
`This should be an identifier from https://spdx.org/licenses/.`

### Actual
`This should be an identifier from https://spdk.org/licenses/.`

The domain redirects to a personal domain https://sphericalduck.org/.

**Comment by bmjen** [comment]
Thanks for that find @farkasmate ! I've opened a JIRA ticket to track this issue.
https://tickets.puppetlabs.com/browse/PDK-543

**Comment by bmjen** [comment]
Thanks for the fix @farkasmate !

Fixed in #303
