### ISSUE TITLE
feature request: pdk publish command

### ISSUE THREAD

**Issue by LongLiveCHIEF** [puppetlabs/pdk#314]
It puts a real hamper in my CI/CD processes when I have to manually go upload a tarball to the forge in order to release a new update.

With a native development solution like this, is it finally time to embrace the final step of the process, and include a `pdk publish` command?

**Comment by DavidS** [comment]
Yes, it is. I've moved it from the informal to the formal roadmap at https://tickets.puppetlabs.com/browse/PDK-579 .

PS: Don't forget to like, and subscribe (that is, vote, and watch on JIRA)!

**Comment by ardrigh** [comment]
As part of this work, is it possible to make the current "deployment" in `.travisci.yml` optional?  Especially if the feature is looking to use `puppet-blacksmith`.

I [opened a PR on the pdk-templates](https://github.com/puppetlabs/pdk-templates/pull/32) but had no reply. 

I feel like having a `pdk publish` command would be better than including this by default in the template CI files.

**Comment by ardrigh** [comment]
Also related issue on pdk-templates https://github.com/puppetlabs/pdk-templates/issues/51

**Comment by ardrigh** [comment]
@DavidS 

Is there still plans to add a `pdk publish` type command? I see `pdk build` was added, but not yet a `publish` component.

If the plan is to add a `publish` command then these sections could drop out of the CI templates, and be replaced by a `~/.puppetforge.yml` config file as per the [puppet-blacksmith docs](https://github.com/voxpupuli/puppet-blacksmith#push-a-module-to-the-puppet-forge)

The reason I am asking is the open PR for the pdk-templates to allow customising the deploy section for TravisCI template, including removing it altogether. 

Either change would save us time having to remember to manually delete the section after doing a `pdk update` :+1:

**Comment by turbodog** [comment]
Yes, we do want to add publishing capabilities though there's no timeline for that right now.

**Comment by scotje** [comment]
There is now a proposed RFC for a new `pdk release` subcommand which would include this functionality. Please add your feedback on the design to the open pull request: https://github.com/puppetlabs/pdk-planning/pull/6

Once accepted, that RFC can be added to the development roadmap.

**Comment by scotje** [comment]
@LongLiveCHIEF @ardrigh https://github.com/puppetlabs/pdk-planning/pull/34 has been proposed to add a `pdk publish` subcommand as an incremental improvement instead of waiting for all of `pdk release` to be implemented.

**Comment by scotje** [comment]
Please review that RFC proposal if you have a moment and give your thoughts.
