### ISSUE TITLE
Feature Request - Questionnaire option to select CI tool

### ISSUE THREAD

**Issue by dhollinger** [puppetlabs/pdk#315]
An additional question would be nice that asks about which CI tool a user is using and providing a template for that.

Popular CI tools suggested for templates:
* Gitlab CI (.gitlab-ci.yml)
* Jenkins (Jenkinsfile)
* Circle CI
* Appveyor (already included)
* Travis (Already Included)

**Comment by DavidS** [comment]
We're currently working on some configurability of the template, and that's a requirement for choosing, especially when private CI systems might require specific setup arguments.

It's also something where community can help out easiest by providing patches to https://github.com/puppetlabs/pdk-module-template ; the more people push their local tweaks upstream, the less maintenance burden they'll have carrying those changes forward.

**Comment by bmjen** [comment]
A ticket to fix the ability to delete a template file via .sync.yml has been generated here: https://tickets.puppetlabs.com/browse/PDK-872.

This fix should allow you to remove the CI configurations you don't need/want, and any missing CI config files that aren't added to pdk-templates can be added via a custom template.

**Comment by scotje** [comment]
`.sync.yml` deletion fix was released in PDK 1.5.0 so I'm going to close this issue for now. If you think removing the undesired CI configurations via `.sync.yml` is an insufficient solution, please open an issue on https://github.com/puppetlabs/pdk-planning describing your use cases. Thank you!
