### ISSUE TITLE
PDK should have an option to disable progress indicator to make it usable in CI

### ISSUE THREAD

**Issue by alvagante** [puppetlabs/pdk#323]
The fancy rotating thing that is shown during pdk validate / test ( [|]  [/] [-] ...] ) results in endless outputs when pdk is used in CI pipelines.
An option to disable it (or the whole removal of the fancy buy mostly useless progress indicator) would make pdk a first choice tool in CI.

**Comment by scotje** [comment]
Seems like a reasonable option. As a temporary measure, you can redirect STDERR to null if you want to suppress the progress output right now:

```
$ pdk validate --format=junit 2>/dev/null
error: task-metadata-lint: tasks/install.json: The property '#/description' of typeinteger did not match the following type: string
```

**Comment by bittner** [comment]
Apart from the progress indicator, can we output a list of the tests the are being executed? Just a normal test progress output, something like [this](https://travis-ci.org/edestecd/puppet-software#L1045) (validate) and [that](https://travis-ci.org/edestecd/puppet-software#L1070) (tests)?

Is this something I can configure myself, or does this depend on PDK?

**Comment by DavidS** [comment]
Some work for this has been captured in https://tickets.puppetlabs.com/browse/PDK-458 and https://tickets.puppetlabs.com/browse/PDK-643 .

**Comment by alvagante** [comment]
Recent versions do the job. Closing.

**Comment by bittner** [comment]
@alvagante Can you explain how this is done, and which those "recent versions" are?

I've just tried PDK v1.5.0, and I can't see how to disable the progress indicator.

```
$ pdk --version
1.5.0
```
No trace of appropriate options, e.g.
```
$ pdk validate --help
NAME
    validate - Run static analysis tests.

USAGE
    pdk validate [validators] [options] [targets]

DESCRIPTION
    Run metadata, Puppet, or Ruby validation.

    [validators] is an optional comma-separated list of validators to use. If
    not specified, all validators are used.

    [targets] is an optional space-separated list of files or directories to
    be validated. If not specified, validators are run against all applicable
    files in the module.

OPTIONS
    -a --auto-correct                Automatically correct problems where
                                     possible.
       --list                        List all available validators.
       --parallel                    Run validations in parallel.
       --pe-version=<value>          Puppet Enterprise version to run tests
                                     or validations against.
       --puppet-version=<value>      Puppet version to run tests or
                                     validations against.

OPTIONS FOR PDK
    -d --debug                       Enable debug output.
    -f --format=<value>              Specify desired output format. Valid
                                     formats are 'junit', 'text'. You may
                                     also specify a file to which the
                                     formatted output is sent, for example:
                                     '--format=junit:report.xml'. This option
                                     may be specified multiple times if each
                                     option specifies a distinct target file.
    -h --help                        Show help for this command.
       --version                     Show version of pdk.
```
:confused:

**Comment by bittner** [comment]
Oh, the presence of an appropriate tty is [detected automatically](https://github.com/puppetlabs/pdk/blob/master/lib/pdk/validate/metadata/task_metadata_lint.rb#L28) and [the redirection can simply be omitted](https://github.com/example42/psick/blob/production/.travis.yml#L12-L18)? Nice! :smiley: :+1:

**Comment by scotje** [comment]
Yep! Sorry we should have linked this PR to this issue: https://github.com/puppetlabs/pdk/pull/353
