### ISSUE TITLE
PDK should have yum/apt/choco repos

### ISSUE THREAD

**Issue by alvagante** [puppetlabs/pdk#324]
On the lines of #323 it would be welcomed a YUM / APT (and eventually choco/whatever fits in macos) repositories to install the pdk package.
The current "download from a redirect link" approach make the unattended installation and upgrade of pdk via puppet classes a bit cumbersome. 
Having package repos would benefit upgrades, and increase the number of people using latest versions.

**Comment by DavidS** [comment]
That work is tracked in https://tickets.puppetlabs.com/browse/PDK-586 et al.

**Comment by alvagante** [comment]
Closing this as it's somehow duplicated.

**Comment by bittner** [comment]
Just in case people come here to look for a solution. Currently, you have to do something like this, which should work for `.travis.yml`, `.gitlab-ci.yaml` and the like:

```yaml
before_script:
  - wget 'https://pm.puppetlabs.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=16.04&arch=amd64&ver=latest' -q -O pdk.deb && dpkg -i pdk.deb && rm pdk.deb
```
