### ISSUE TITLE
Expose other executables into main bin directory

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk#328]
I want to use the git that ships with the pdk but it is nested inside a private directory.

/opt/puppetlabs/pdk/private/git/bin

I also want to use gem, irb, and ruby and any other executables that get shipped with gems

**Comment by rodjek** [comment]
Hi @logicminds,

You can call out to any of the ruby commands or executables shipped in gems using the `pdk bundle` subcommand (e.g. `pdk bundle exec irb`, `pdk bundle exec puppet-lint`).

In regards to git though, the decision not to expose it was deliberate and we strongly recommend that you do not depend on it. It is there as an internal component of the PDK and will likely be replaced with libgit2 at some point in the future.

**Comment by logicminds** [comment]
RHEL 6 ships with git 1.8.1 which has a few annoying bugs.  I think many people would enjoy not having a separate package to install / download.  Having a recent git version would be another benefit to using PDK because it ships with everything you need.  I would agree that Rugged would just wrap a bunch of workflows and negate the need for git on the command line.  But I am not convinced removing git as a tool away from a developer is the right decision when they still need to learn git to perform other tasks.

**Comment by DavidS** [comment]
One of our goals with the PDKis to not be intrusive into advanced user's workflows (at least not more than necessary). Shipping a plain `git` binary on the default path is borderline risky in that regard.

I've put up an experiment at #331
