### ISSUE TITLE
Support for future parser on Puppet < 4.0.0

### ISSUE THREAD

**Issue by jeremy-asher** [puppetlabs/pdk#330]
It doesn't seem that there's support for testing against the future parser on older Puppet versions.  In the past, I've seen this set with the environment variable `FUTURE_PARSER` (https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/rake_tasks.rb#L509).  I'm guessing a CLI option makes more sense with PDK.

**Comment by DavidS** [comment]
The PDK only supports puppet 4 and later.

That said, it's still using puppetlabs_spec_helper under the hoods, so you'll be able to use the existing configuration hooks until we eventually phase out puppet 3 support code completely.

**Comment by jeremy-asher** [comment]
Fair enough, though this config of puppetlabs_spec_helper is not honored by PDK.  It was a little unclear that older versions are unsupported especially considering the number of fixes the templates have for the 3 series of Puppet:
https://github.com/puppetlabs/pdk-module-template/blob/master/moduleroot/Gemfile.erb#L114-L170

**Comment by DavidS** [comment]
Are you saying that setting `FUTURE_PARSER=yes` when running tests against puppet 3, using the `pdk` tool, doesn't actually configures the future parser for this run?

**Comment by jeremy-asher** [comment]
Yes.  That is the case, unfortunately.  I don't believe puppet-syntax is really used by PDK at this point.

**Comment by DavidS** [comment]
`pdk validate` uses puppet-syntax.

Are you *sure* that you're running against puppet3? e.g. does `pdk bundle -- exec puppet --version` output the correct info? The PDK by default would only install/use the newest puppet5

**Comment by jeremy-asher** [comment]
Yes, I am setting the environment variables for the Puppet and Facter gems:
```
[root@5ff325bb368b test-module]# env | grep GEM
PUPPET_GEM_VERSION=3.8.7
FACTER_GEM_VERSION=2.4.6
```

```
[root@5ff325bb368b test-module]# pdk bundle -- exec puppet --version
3.8.7
```

Sorry, I should have been a bit more clear about the issue.  Here's what I'm seeing:
```
[root@5ff325bb368b test-module]# pdk validate
pdk (INFO): Running all available validators...
[✔] Checking metadata syntax (metadata.json tasks/*.json).
[✔] Checking module metadata style (metadata.json).
[✖] Checking Puppet manifest syntax (**/**.pp).
[✔] Checking Ruby code style (**/**.rb).
info: task-metadata-lint: ./: Target does not contain any files to validate (tasks/*.json).
Error: Could not parse for environment production: puppet-syntax: Syntax error
```

```
[root@5ff325bb368b test-module]# cat manifests/init.pp
# test_module
class test_module (
  String $typed_variable,
) { }
```

What I meant about not using puppet-syntax is that the `puppet parser validate` command is being used instead for validating syntax of `.pp` files.  With `--debug`:
```
[root@5ff325bb368b test-module]# pdk validate --debug
pdk (INFO): Running all available validators...
pdk (DEBUG): Checking for missing Gemfile dependencies.
pdk (DEBUG): Using 'private/ruby/2.1.9/bin/bundle' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle check --gemfile=/tmp/test-module/Gemfile'
pdk (DEBUG): Command environment: GEM_HOME is '/root/.pdk/cache/ruby/2.1.0' and GEM_PATH is '/opt/puppetlabs/pdk/share/cache/ruby/2.1.0'
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle check --gemfile=/tmp/test-module/Gemfile' complete (duration: 0.402515641s; exit code: 0)
pdk (DEBUG): Executing '/tmp/test-module/bin/metadata-json-lint --format json --strict-dependencies /tmp/test-module/metadata.json'
pdk (DEBUG): Command environment: GEM_HOME is '/root/.pdk/cache/ruby/2.1.0' and GEM_PATH is '/opt/puppetlabs/pdk/share/cache/ruby/2.1.0'
pdk (DEBUG): Execution of '/tmp/test-module/bin/metadata-json-lint --format json --strict-dependencies /tmp/test-module/metadata.json' complete (duration: 0.851438212s; exit code: 0)
pdk (DEBUG): task-metadata-lint: Skipped '/tmp/test-module'. Target does not contain any files to validate (tasks/*.json).
pdk (DEBUG): Executing '/tmp/test-module/bin/puppet parser validate /tmp/test-module/manifests/init.pp'
pdk (DEBUG): Command environment: GEM_HOME is '/root/.pdk/cache/ruby/2.1.0' and GEM_PATH is '/opt/puppetlabs/pdk/share/cache/ruby/2.1.0'
pdk (DEBUG): Execution of '/tmp/test-module/bin/puppet parser validate /tmp/test-module/manifests/init.pp' complete (duration: 3.035234528s; exit code: 1)
pdk (DEBUG): Executing '/tmp/test-module/bin/rubocop --format json /tmp/test-module/spec/spec_helper.rb'
pdk (DEBUG): Command environment: GEM_HOME is '/root/.pdk/cache/ruby/2.1.0' and GEM_PATH is '/opt/puppetlabs/pdk/share/cache/ruby/2.1.0'
pdk (DEBUG): Execution of '/tmp/test-module/bin/rubocop --format json /tmp/test-module/spec/spec_helper.rb' complete (duration: 1.285657725s; exit code: 0)
info: task-metadata-lint: ./: Target does not contain any files to validate (tasks/*.json).
Error: Could not parse for environment production: puppet-syntax: Syntax error
```

https://github.com/puppetlabs/pdk/blob/master/lib/pdk/validators/puppet/puppet_syntax.rb#L25

Since this command is being used directly, the typical env vars used by the puppet-syntax Gem are not applicable.
