### ISSUE TITLE
Add `new control` command for creating control repository

### ISSUE THREAD

**Issue by bittner** [puppetlabs/pdk#333]
PDK should support creating and extending a [control-repository](https://puppet.com/docs/pe/latest/code_management/control_repo.html), which is enabled for validation and testing using PDK (just like the modules created by PDK).

Obsoletes #289 and #332 when implemented.
See also: https://github.com/puppetlabs/control-repo/issues/52

Proposed Solution
-------------------

Ideally,

- the validation and test setup currently present in generated modules should be taken over to the proposed [Puppet Labs control-repo](https://github.com/puppetlabs/control-repo), and
- the `pdk new control` command should generate a control-repo setup that is equivalent to the proposed Puppet Labs control-repo on GitHub.

This way, whether you use PDK or just the GitHub repo as an example, you can trust to get a usable best-practice setup.

**Comment by cdenneen** [comment]
@bittner except for the metadata.json check the validation will work on existing control repo so far that I can tell.
The ability to generate a control repo would definitely need to be added and skip the metadata.json check in those cases.

**Comment by bittner** [comment]
The `Gemfile` is needed to make `pdk validate` work on a control repo, see https://github.com/puppetlabs/pdk/issues/289#issuecomment-339000049.

The `Rakefile`, `.fixtures.yml` (with `links:` to the `roles` and `profiles` folders, and more dependencies specified in the `forge_modules:` section), `spec/spec_helper.rb` and specs in `spec/classes/` is needed for `pdk test unit`.

Not sure how the `examples/` would come into play. Then there are also acceptance tests (as seen in the [PSICK repo](https://github.com/example42/psick/tree/production/skeleton/spec)). If that all makes sense it must be generated, and work out of the box. :+1:

**Comment by ardrigh** [comment]
I was talking with my team about the files PDK adds when it converts modules, so that it can run the tests and validation.

Currently our control repo has 40+ internal Puppet modules, and converting them all with PDK would potentially add a huge number of duplicate files (Gemfile etc).

It would be good to know if support for testing across control repos is still on the development plan. 

I am hopeful we will eventually be able migrate our TravisCI setup to test our control repo solely using simple PDK commands

**Comment by ardrigh** [comment]
Additional question, has any thought been given to integrating the [onceover](https://github.com/dylanratcliffe/onceover) gem into PDK for control repo testing?

**Comment by Nekototori** [comment]
I'd second onceover.  PDK is to modules as onceover is to control repos (as it stands today).

**Comment by scotje** [comment]
This issue was moved to puppetlabs/pdk-planning#10
