### ISSUE TITLE
PDK `test unit` should cache downloaded modules

### ISSUE THREAD

**Issue by bittner** [puppetlabs/pdk#339]
When PDK runs unit tests all fixtures (dependencies) are downloaded afresh and deleted completely after completion of the test run.

This is convenient, but when you have a lot of external dependencies (`forge_modules` or `repositories` in your `.fixtures.yml` file) the _"Preparing to run the unit tests"_ step simply takes too long to execute in a test run.

Proposed Solution
----------------

PDK's `test` command should

- either _always cache_ downloaded fixtures, and provide both a `--no-cache` option to ignore the cache and a `pdk clean` command to remove downloaded fixtures manually (All test execution frameworks I know do it like this)
- or have a `--cache-fixtures` option to stop PDK from deleting the downloaded fixtures

**Comment by DavidS** [comment]
We are tracking that in [PDK-636](https://tickets.puppetlabs.com/browse/PDK-636). See [PDK-381](https://tickets.puppetlabs.com/browse/PDK-381) for background.

**Comment by rodjek** [comment]
This has been implemented in PDK 1.6.0 :) `pdk test unit` will now cache the downloaded test fixtures by default, and a `--clean-fixtures` flag has been added to `pdk test unit` to restore the original behaviour when needed (useful for CI runs).
