### ISSUE TITLE
Internal Server Error on PDK Download site

### ISSUE THREAD

**Issue by bittner** [puppetlabs/pdk#348]
Not sure if you guys have already noticed, but the download site seems to be broken.

All the [links to PDK packages](https://puppet.com/download-puppet-development-kit) (installers) of the various OS flavors lead to an Error 500 page.

**Comment by scotje** [comment]
Thanks @bittner, I've passed this along to our release engineering team for triage.

**Comment by scotje** [comment]
The download links should be working again now, sorry for the inconvenience!
