### ISSUE TITLE
Don't buffer output from bundle commands

### ISSUE THREAD

**Issue by luyseyal** [puppetlabs/pdk#364]
When I run `bundle exec rake spec`, I see output immediately. When I run `pdk bundle exec rake spec`, I have to wait until the end to see output. We have a zillion tests. Is there some way to disable buffering STDIN -> STDOUT (or whatever...)?

**Comment by scotje** [comment]
This is tracked in JIRA as https://tickets.puppetlabs.com/browse/PDK-641

**Comment by scotje** [comment]
This was fixed in PDK 1.12.0! 🎉
