### ISSUE TITLE
Puppet and PDK T-Shirts

### ISSUE THREAD

**Issue by bittner** [puppetlabs/pdk#381]
We're moving our whole developer team to PDK, making them use Puppet to shape their own (development) infrastructure in a DevOps manner.

Now, there should be t-shirts to get the hype out to the crowd.

I've seen an [old blog post on t-shirts](https://puppet.com/blog/t-shirt-contest). Is there a more recent source for getting swag for the team?

**Comment by bittner** [comment]
Thanks, @DavidS!

[T-shirts arrived](https://www.facebook.com/comsolit/photos/a.314646026021.157733.51873456021/10155003832156022/?type=3&theater) just when I talked about this ticket in our last retro before Christmas! Thanks so much! :smile:

**Comment by DavidS** [comment]
Ya'll look sharp in the new swag! Keep us posted how the pdk works out for you.
