### ISSUE TITLE
Add switch to make PDK validate fail on warnings

### ISSUE THREAD

**Issue by bittner** [puppetlabs/pdk#392]
`pdk validate` currently passes successfully when warnings are spit out.

It should be possible to pass a command line option, e.g. ` --fail-warnings`, to make `pdk validate` fail on warnings.

**Comment by bmjen** [comment]
Thanks @bittner we created https://tickets.puppetlabs.com/browse/PDK-909 to track this feature request!

**Comment by PaulSD** [comment]
Looks like this was implemented here:
https://tickets.puppetlabs.com/browse/PDK-1417
https://github.com/puppetlabs/pdk-templates/pull/265

**Comment by bittner** [comment]
Nice! IIUC there is no command line switch for that, though. You have to enable the feature via `.puppet-lint.rc`.

Can this feature be made available via a command line switch, too?

**Comment by sanfrancrisko** [comment]
This ticket will not be addressed in it's current form, but the issue will be considered in the future roadmap of the new PDK: https://puppet.com/blog/the-future-of-the-puppet-developer-kit-pdk/
