### ISSUE TITLE
Update shipped ruby

### ISSUE THREAD

**Issue by tebeco** [puppetlabs/pdk#395]
hello,
I just tried to run a “pdk validate” on a working repository and i encounter a crash on the Bundler.rb shipped with latest PDK

see https://github.com/rubygems/rubygems/issues/1668

is there a was to either ask that the ruby is updated or it there’s a process scan easily follow so i can update it on my own ?

PS: I’m new to puppet and ruby ;)

**Comment by DavidS** [comment]
Hi,

I haven't been able to reproduce that on the quick:

```
david@davids:~/git/tmp$ pdk new module foo --skip-interview
pdk (INFO): Creating new module: foo
pdk (INFO): Module 'foo' generated at path '/home/david/git/tmp/foo', from template 'file:///opt/puppetlabs/pdk/share/cache/pdk-templates.git'.
pdk (INFO): In your module directory, add classes with the 'pdk new class' command.
david@davids:~/git/tmp$ cd foo/
david@davids:~/git/tmp/foo$ pdk new class foo
pdk (INFO): Creating '/home/david/git/tmp/foo/manifests/init.pp' from template.
pdk (INFO): Creating '/home/david/git/tmp/foo/spec/classes/foo_spec.rb' from template.
david@davids:~/git/tmp/foo$ pdk validate
pdk (INFO): Running all available validators...
[✔] Checking metadata syntax (metadata.json tasks/*.json).
[✔] Checking module metadata style (metadata.json).
[✔] Checking Puppet manifest syntax (**/**.pp).
[✔] Checking Puppet manifest style (**/*.pp).
[✔] Checking Ruby code style (**/**.rb).
info: task-metadata-lint: ./: Target does not contain any files to validate (tasks/*.json).
david@davids:~/git/tmp/foo$ pdk bundle -- --version
Bundler version 1.15.1
The latest bundler is 1.16.0, but you are currently running 1.15.1.
To update, run `gem install bundler`

david@davids:~/git/tmp/foo$ 
```

and the pdk is deliberately not using the latest bundler, since that has its own problems with puppet.

Please provide more info on what you're seeing. If you can provide a git repo of your module, that would also help to diagnose.

**Comment by tebeco** [comment]
cannot test until the end of january ...
i’ll reopen the issue if i work again on that feature

FYI: The puppet recipe runs perfectly on the agent
the only thing i did was adding Puppet Dev Kit (latest)
then in vscode with puppet extensions, tried to run a `pdk validate` from the extension commands 

closing for now

**Comment by tebeco** [comment]
@davejohnston had an issue with SSL certificate that changed due to SHA1 depracation
I had to update rubygem to 2.7.x manually

http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages
