### ISSUE TITLE
"pdk convert" and "pdk new module" fails on OSX Sierra

### ISSUE THREAD

**Issue by natemccurdy** [puppetlabs/pdk#396]
**PDK**: 1.3.0
**OS**: OSX Sierra 10.12

When doing a `pdk convert` in an existing module or when creating a new module, I get the following error:

```
pdk (ERROR):
pdk (ERROR): fatal: ambiguous argument '1.3.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

pdk (FATAL): Unable to set git repository '/var/folders/ss/b33hxsf54bx0rbg0gqjd1yr40000gq/T/pdk-templates20171219-99977-154j6im' to ref:'1.3.0'.
```

**Comment by natemccurdy** [comment]
The git repo at that path in `/var/folders` has a remote that points to:

`https://github.com/puppetlabs/pdk-module-template`

That repo does not have a tag for 1.3.0.

Seems like that template repo should be https://github.com/puppetlabs/pdk-templates instead

**Comment by natemccurdy** [comment]
The culprit was `~/.pdk/cache/answers.json` that contained the old templates repo URL. Deleting that json file fixed the problem.

But, an upgrade to 1.3.0 from an older version should handle that more cleanly.

Thanks for the help @scotje !

**Comment by scotje** [comment]
Created https://tickets.puppetlabs.com/browse/PDK-736 to track a more complete fix for this.

**Comment by natemccurdy** [comment]
Looks like this is resolved in https://github.com/puppetlabs/pdk/pull/397

I'll close this ticket. Thanks!
