### ISSUE TITLE
WS1.Reputation - Symantec Endpoint Protection

### ISSUE THREAD

**Issue by TJM** [puppetlabs/pdk#403]
Symantec Endpoint Protection is "catching" the installation of PDK 1.3.1.0 (I think it also caught 1.3.0.0). 

Here is the message from SEP:

```
Scan type: Auto-Protect Scan

Event: Security Risk Found!

Security risk detected: WS.Reputation.1

File: c:\users\username\downloads\pdk-1.3.1.0-x64.msi

Location: Deleted or access blocked
...
```

I found this information: https://support.symantec.com/en_US/article.TECH132220.html

**Comment by TJM** [comment]
Awesome! Thanks.

**Comment by DavidS** [comment]
@TJM we have that now in our release process (https://github.com/puppetlabs/pdk-vanagon#promoting-and-releasing-new-packages , # 12). Did that clear up your reports?

**Comment by TJM** [comment]
@DavidS Confirmed! I just tried 1.3.2.0 and did not receive any warnings. Thanks!

**Comment by DavidS** [comment]
Thanks!

**Comment by DavidS** [comment]
PS: Note that Symantec takes "a while" to update their database, so future whitelisting might lag behind new releases a couple of days.
