### ISSUE TITLE
Any interest in adding a `--parallel` option to `pdk test unit`?

### ISSUE THREAD

**Issue by mdwheele** [puppetlabs/pdk#446]
There are several options for running RSpec specifications in parallel to speed up test-runs. Would this project be interested in any contributions to add this? I would be happy to help.

**Comment by hunner** [comment]
The rake task of puppetlabs_spec_helper uses the parallel_spec gem: https://github.com/puppetlabs/puppetlabs_spec_helper/blob/v2.6.2/lib/puppetlabs_spec_helper/rake_tasks.rb#L461 if that helps make adding it easier.

**Comment by rodjek** [comment]
@mdwheele `pdk test unit --parallel` has already been implemented but it is currently an experimental feature and so is hidden from the help output. Give it a try and let us know if you run into any issues with it :)
