### ISSUE TITLE
Support for template URL with a branch

### ISSUE THREAD

**Issue by bodgit** [puppetlabs/pdk#447]
It would be handy to be able to specify a branch when providing a template URL. https://github.com/puppetlabs/pdk/blob/fffe46a617d37b8bd095d44d1245bb23a5bdffb8/lib/pdk/util.rb#L204 alludes to maybe adding such an option.

**Comment by scotje** [comment]
Yep! See #434 hopefully this will be landing soon!

**Comment by bodgit** [comment]
Sorry, not sure how I missed that PR :smile:
