### ISSUE TITLE
feature request: pdk test unit should provide for presenting log output

### ISSUE THREAD

**Issue by jcbollinger** [puppetlabs/pdk#463]
The `pdk test unit` CLI should provide an option or options for presenting the catalog builder's log output to the user, such as is generated by Puppet's `debug()`, `notice()`, _etc_. functions.  Note that I am merely asking to see the log output, not to test it.  This can be of great benefit for determining _why_ tests fail.  Even something as simple as a `--loglevel` option, defaulting to 'none', would be a tremendous help.

I've had a go at tweaking my tests and the spec_helper to get the output, without success.  I'm uncertain whether that's because I've made the wrong mods or because `pdk test unit` is squashing the output, but in the end, I don't care.  The reason to choose PDK or a similar tool is to avoid having to do that kind of thing myself in the first place.

**Comment by rodjek** [comment]
rspec-puppet changes tracked in https://github.com/rodjek/rspec-puppet/issues/672

**Comment by jcbollinger** [comment]
Again, I am am still interested in having this feature implemented.

**Comment by jcbollinger** [comment]
I would still like this feature.

**Comment by LukasAud** [comment]
Hi @jcbollinger, sorry for the long delay in response. We are looking at your issue and think it may be a nice quality of life upgrade. However, we cannot afford to prioritise this piece of work at the moment as we are working on other projects. Feel free to open a PR and share it with our open-source community if you want any help with it.
