### ISSUE TITLE
PDK packaging should include all needed gems

### ISSUE THREAD

**Issue by jcbollinger** [puppetlabs/pdk#467]
I recently tried to upgrade from PDK 1.4.1.1 to PDK 1.4.1.2 performing a `yum update pdk`.  The package was downloaded fine from Puppet's puppet5 repository, and installation completed without any error, but `pdk` would not run:

```
$ pdk validate
pdk (INFO): Running all available validators...
[✖] Installing missing Gemfile dependencies.
pdk (FATAL): Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/


pdk (FATAL): Unable to install missing Gemfile dependencies.
```
This very likely arises in part because my particular development environment is subject to fairly tight network access restrictions (I had to obtain special dispensation to enable connections to yum.puppetlabs.com), but that's quite beside the point: the RPM packaging ought not to require any gems to be downloaded from rubygems.org in the first place.  Anything not included in the tin with PDK itself should be available in RPM form (possibly as an RPM-wrapped gem), and listed among PDK's RPM dependencies.

Downgrading to 1.4.1.1 restored function.

RedHat Enterprise 7.4
x86_64

**Comment by scotje** [comment]
You are correct that the required gems are supposed to be bundled into the package. We will investigate, but if you have a chance to run the `1.4.1.2` version again with the `--debug` flag that would also help us diagnose.

**Comment by jcbollinger** [comment]
Here's the full output of `pdk validate --debug` with PDK 1.4.1.2, as installed via the pdk-1.4.1.2-1.el7.x86_64 rpm from the puppet5 repository at yum.puppetlabs.com:
```
$ pdk validate --debug
pdk (INFO): Running all available validators...
pdk (DEBUG): Checking for missing Gemfile dependencies.
pdk (DEBUG): Using 'private/ruby/2.1.9/bin/bundle' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle check --gemfile=/home/whitegrp/jbolling/puppet-clone/code/environments/production/modules/sb/Gemfile'
pdk (DEBUG): Command environment: GEM_HOME is '/home/whitegrp/jbolling/.pdk/cache/ruby/2.1.0' and GEM_PATH is '/opt/puppetlabs/pdk/share/cache/ruby/2.1.0'
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle check --gemfile=/home/whitegrp/jbolling/puppet-clone/code/environments/production/modules/sb/Gemfile' complete (duration: 0.238321791s; exit code: 1)
pdk (DEBUG): The following gems are missing
 * gettext (3.2.6)
 * rspec-puppet (2.6.9)
 * facterdb (0.5.0)
 * parser (2.5.0.2)
 * docile (1.1.5)
 * simplecov (0.15.1)
Install missing gems with `bundle install`


pdk (DEBUG): Using 'private/ruby/2.1.9/bin/bundle' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle install --gemfile=/home/whitegrp/jbolling/puppet-clone/code/environments/production/modules/sb/Gemfile -j4'
pdk (DEBUG): Command environment: GEM_HOME is '/home/whitegrp/jbolling/.pdk/cache/ruby/2.1.0' and GEM_PATH is '/opt/puppetlabs/pdk/share/cache/ruby/2.1.0'
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle install --gemfile=/home/whitegrp/jbolling/puppet-clone/code/environments/production/modules/sb/Gemfile -j4' complete (duration: 0.917277242s; exit code: 17)
pdk (FATAL): Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/


pdk (FATAL): Unable to install missing Gemfile dependencies.
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-1.4.1/lib/pdk/util/bundler.rb:44:in `ensure_bundle!'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-1.4.1/lib/pdk/cli/validate.rb:84:in `block (2 levels) in <module:CLI>'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:319:in `call'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:319:in `run_this'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:264:in `run'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-1.4.1/lib/pdk/cli.rb:17:in `run'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-1.4.1/exe/pdk:6:in `<top (required)>'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/bin/pdk:23:in `load'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/bin/pdk:23:in `<main>'
```

**Comment by jcbollinger** [comment]
I have not written or customized any PDK templates, and no one else has access to do so in the particular development environment affected, so I assume I am using the default templates.  I had made some minor (IMO) changes to `spec_helper.rb`.  The `pdk update` command reverted these changes, but did not modify any other files.  This did not solve the problem -- `pdk validate` still fails, with the same output, and other PDK subcommands such as `pdk test unit` fail with similar output.

**Comment by jcbollinger** [comment]
I also tried moving the `.pdk` subdirectory in my home directory out of the way, as if I were personally starting fresh with an existing PDK-based module.  This also was ineffective.

**Comment by scotje** [comment]
@jcbollinger Hmmm, 1.4.1.2 was one of our first releases where nothing about PDK itself changed, only some of the bundled supporting software, so I think we're hitting an edge case where not enough has changed for `pdk update` to do everything it needs to do to resolve things.

While we investigate further, can you try removing (or making a copy of) the `Gemfile.lock` file in your module root and then replacing it with a copy of `/opt/puppetlabs/pdk/share/cache/Gemfile.lock`?

**Comment by jcbollinger** [comment]
Replacing the module's `Gemfile.lock` with a copy of the designated one in the PDK 1.4.1.2 distribution resolved the errors for me, so it seems to be a viable workaround.  Thanks.

**Comment by bmjen** [comment]
Ticket to track the prompt to run `pdk update` is here: https://tickets.puppetlabs.com/browse/PDK-904

**Comment by scotje** [comment]
And the other ticket is https://tickets.puppetlabs.com/browse/PDK-910
