### ISSUE TITLE
PDK should support integration testing

### ISSUE THREAD

**Issue by jcbollinger** [puppetlabs/pdk#481]
PDK seems to be tightly focused on supporting the development of individual modules, and it is very useful in that area, but individual modules are not end of the story.  Site configurations are built of many modules employed together.  It is combinatorically difficult to test modules against every constellation of supported versions of all of their dependencies, and in practice, it is not done.  It is even more difficult to anticipate all the forms and and combinations of site data that might be presented to modules. PDK does not help with those things, and it cannot reasonably be expected to do.

But what PDK could and should do is support testing against the *specific* constellation of modules, site manifest, and site data that a user happens to want to deploy at their particular site.  From an rspec-puppet perspective, I picture this being set up as a framework for running a collection of host tests against (a clone of) the site's actual whole configuration as an integrated unit.

**Comment by scotje** [comment]
This issue was moved to puppetlabs/pdk-planning#15
