### ISSUE TITLE
PDK fails to checkout template from git repo on CentOS 7

### ISSUE THREAD

**Issue by nabertrand** [puppetlabs/pdk#490]
CentOS 7 ships with git version 1.8.3, which does not support the '-C' option. This causes PDK to fail if a template URL is provided.

```
$ pdk new module --template-url https://github.com/puppetlabs/pdk-templates --skip-interview test
pdk (INFO): Creating new module: test
pdk (ERROR): 
pdk (ERROR): Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

pdk (FATAL): Unable to set git repository '/tmp/pdk-templates20180426-3060-lj5b7d' to ref:'1.4.1'.
$ pdk --version
1.4.1
$ uname -a
Linux client 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```

https://github.com/puppetlabs/pdk/blob/acf14899d7c5b3e0bae22f38a40bde7b1d9a0fe8/lib/pdk/module/templatedir.rb#L295

**Comment by rodjek** [comment]
@nabertrand did you install PDK from an RPM or gem?

**Comment by nabertrand** [comment]
This was a gem install. I can confirm the problem does not seem to exist when installed from the RPM. It looks like the RPM actually ships with its own git. I'm attempting to run pdk commands from a Jenkins pipeline and was hoping to be able to use the gem.

**Comment by rodjek** [comment]
Yep, we highly recommend using the native packages for that reason. They include vendored versions of git and ruby that we have tested and ensure to be working. I recommend that you install the RPM on your Jenkins build hosts to make the PDK commands available during test runs rather than using the gem.

**Comment by nabertrand** [comment]
I'll switch to the RPM install then. Thanks for the quick reply.

**Comment by scotje** [comment]
I think #602 should resolve this specific issue starting with PDK 1.9.0
