### ISSUE TITLE
Configure 'ordering' for rspec-puppet in PDK

### ISSUE THREAD

**Issue by ardrigh** [puppetlabs/pdk#511]
I just found after reading through documentation that Puppet and rspec-puppet handle ordering in different ways.

Currently rspec-puppet defaults to "title-hash" and Puppet 5.5 defaults to "manifest".

The difference between 

> will order resources randomly, but will use the same order across runs

and 

> will use the order in which the resources were declared in their manifest files

seems significant enough to make more explicit for users writing tests. This is especially true if random ordering requires additional lines of code to avoid breaking.

It will help improve the user experience with people new to writing tests if the test tools and Puppet itself are consistent in behaviour.

https://github.com/rodjek/rspec-puppet#ordering
https://puppet.com/docs/puppet/4.6/configuration.html#ordering
https://puppet.com/docs/puppet/5.5/configuration.html#ordering

I have also logged a ticket https://github.com/rodjek/rspec-puppet/issues/689 related to the default value.

Is it reasonable to have a configuration option for this?

**Comment by scotje** [comment]
Thanks for bringing this up! This will addressed via the rspec-puppet issue you filed, at which point PDK will pick up the new behavior.
