### ISSUE TITLE
Creating packages from this repo

### ISSUE THREAD

**Issue by agargiulo** [puppetlabs/pdk#519]
Is there any documentation/guidance on how to package the code from this repo into what's available on the release/downloads page? I was looking to possibly package this for something not in the official list.

**Comment by scotje** [comment]
@agargiulo The packaging configuration for PDK is contained in the https://github.com/puppetlabs/pdk-vanagon repository. It's a bit of a challenge to get it up and running outside of our internal infrastructure but it should theoretically be possible.

We have recently added some additional configurations to that repo however so there will be a handful of additional platforms supported with the next release later this month, so depending on what you wanted to target it might already be in the pipeline. :)

The pending platforms are:

- Ubuntu 18.04
- macOS 10.13
- Debian 8
- Debian 9
- Fedora 26
- Fedora 27

**Comment by scotje** [comment]
Sounds good! I'm going to close this issue for now but please let us know if there is anything else we can do to help.
