### ISSUE TITLE
pdk not supporting AIX as a testable operatingsystem type

### ISSUE THREAD

**Issue by halloweenjacksla** [puppetlabs/pdk#520]
Running pdk on a windows 10 node

 **metadata.json**     
      "operatingsystem": "AIX",
      "operatingsystemrelease": [
        "7.0",
        "6.0"
returns 
pdk test unit
[*] Preparing to run the unit tests.
[*] Running unit tests.
No examples found.
  Evaluated 0 tests in 0.0 seconds: 0 failures, 0 pending.
[*] Cleaning up after running unit tests.

**metadata.json**
      "operatingsystem": "RedHat",
      "operatingsystemrelease": [
        "7.0",
        "6.0"
returns
pdk test unit
[*] Preparing to run the unit tests.
[X] Running unit tests.
  Evaluated 14 tests in 3.107317 seconds: 8 failures, 0 pending.
[*] Cleaning up after running unit tests.

**Comment by rodjek** [comment]
This is happening because [facterdb](https://github.com/camptocamp/facterdb) doesn't have many fact sets for AIX. I've opened a ticket in Jira to track generating these fact sets and getting them added to facterdb: https://tickets.puppetlabs.com/browse/PDK-1052
