### ISSUE TITLE
pdk 1.5 seems to drop environment variables that enable socks proxy functionality

### ISSUE THREAD

**Issue by JakeTRogers** [puppetlabs/pdk#521]
I have a tsocks proxy between my laptop and the bitbucket server. Prior to 1.5 I am able to use pdk successfully. However it seems that 1.5's method of cloning repos causes it to loose the environment variables that control my socks proxy configuration. Causing the pdk clone operations to fail to reach our bitbucket server.

On a working shell session that can reach bitbucket server with a git cmd, I have the following ENV var, which is i suspect being lost by PDKs repo cloning process:
LD_PRELOAD=/usr/lib64/libtoxsockv3.so

Unable to upgrade beyond 1.4.x due to this issue.

**Comment by scotje** [comment]
`LD_PRELOAD` is something we likely cannot safely propagate to our subprocesses, but we could make sure that some proxy specific environment variables are propagated. Is there a reason that you have to configure your proxy specifically through `LD_PRELOAD`?

**Comment by scotje** [comment]
For example, can you configure your proxy for PDK commands like so:  `ALL_PROXY=socks5://proxy.example:8080 pdk new module test_with_proxy`?

**Comment by JakeTRogers** [comment]
my employer uses this toxsocks software for the proxy and so when I run toxsocks <some_app> it appears it is adding LD_PRELOAD env var and then that app is able to pass stuff through the proxy.

This all worked great in 1.4 and earlier PDK releases. I tried as you suggested unsuccessfully to specify the IP of my proxy from the toxsocks config and then trying to run my spec tests with pdk. The proxy is only required to reach the bitbucket server, running in a customer datacenter, not to reach the internet in general. thanks!

**Comment by JakeTRogers** [comment]
I was able to work around this with the ~/.ssh/config file and using proxyCommand directive which forced any connection attempted over ssh to my bitbucket server to invoke toxsocks first.

**Comment by scotje** [comment]
@JakeTRogers Glad you were able to find a solution!
