### ISSUE TITLE
Creating test skeletons

### ISSUE THREAD

**Issue by SwampFalc** [puppetlabs/pdk#525]
Hello,

Just a moment ago I used `pdk convert` to convert an old module I had lying around, which had 3 classes.
Unfortunately, `pdk convert` does not create the unit test skeletons for existing classes.
And `pdk new <class>`, which does create those test skeletons, doesn't work on an existing class.

The fact that this functionality is present in PDK but just doesn't seem to be available to me in any way in this particular use case is quite frustrating.

**Comment by RARYates** [comment]
On the PSE in the field side, this would be great for universally every Puppet organization making the switch.

**Comment by natemccurdy** [comment]
+1 to this. A command like `pdk new spec <class_name>` to build a spec test for an *existing* class would be great!

**Comment by logicminds** [comment]
You can use `puppet retrospec` to fill the gap here. It will create spec tests based on the existing code.

https://www.retrospec-puppet.com/

**Comment by sanfrancrisko** [comment]
Thanks for the follow up @natemccurdy
