### ISSUE TITLE
PDK 1.6.0: c.hiera_config double quotes creates rubocop warning

### ISSUE THREAD

**Issue by ardrigh** [puppetlabs/pdk#530]
There was an update in https://github.com/puppetlabs/pdk-templates/pull/72 to the template for `spec/spec_helper.rb` around the `c.hiera_config` path. 

This change now creates a rubocop warning about the double quotes around the value.

```diff
-  c.hiera_config = 'spec/fixtures/hiera/hiera.yaml'
+  c.hiera_config = "spec/fixtures/hiera/hiera.yaml"
```

```shell
convention: rubocop: spec/spec_helper.rb:34:20: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
```

I understand the reason for adding quotes, but not sure how the single vs double quotes can be managed in a template.

**Comment by rodjek** [comment]
Thanks @ardrigh, I've opened a PR on puppetlabs/pdk-templates to address this

**Comment by rodjek** [comment]
The change to template has been merged :)
