### ISSUE TITLE
PDK 1.6.0: parallel_spec causes Puppet coverage reports to change badly

### ISSUE THREAD

**Issue by ardrigh** [puppetlabs/pdk#531]
I won't say code coverage reports are now broken, because technically they are running, but the output has certainly changed a lot.

With the previous versions of PDK running a code coverage report in TravisCI was fairly straight forward, adding in the section to the `spec/spec_helper.rb` file.

That's now all changed by the use of the parallel_spec tests, causing each of the test manifests to run and complain about different lists of missing resources.

Is there any way to get Puppet code coverage reports that make sense? I know I don't have 5% test coverage because everything was fine until I updated my module to PDK 1.6.0

This is the entry in my `spec/spec_helper.rb` file:

```ruby
RSpec.configure do |c|
  c.after(:suite) do
    RSpec::Puppet::Coverage.report!(95)
  end
end
```

I am not sure if there needs to be another task to run for coverage tests separately?

PDK creates a separate spec file for each class, define, etc. I assume the coverage report might work if all the code was in a single spec file, but that would require changing all my spec files.

**Comment by ardrigh** [comment]
See also https://github.com/rodjek/rspec-puppet/issues/624

**Comment by ardrigh** [comment]
It looks like this will be resolved in rspec-puppet 2.6.14 release +1

**Comment by scotje** [comment]
The new version of rspec-puppet should be included in the next PDK release. Thanks for the bug report!

**Comment by bmjen** [comment]
Resolved on the PDK side in https://tickets.puppetlabs.com/browse/PDK-1051 and will be in 1.6.1
