### ISSUE TITLE
r10k puppetfile install return r10k/cli (LoadError)

### ISSUE THREAD

**Issue by danielserrao** [puppetlabs/pdk#534]
Hi,

In my Gemfile I have:

```
gem 'rake', '12.3.0'
gem 'r10k', '2.1.0'
gem 'ra10ke', '0.1.1'
...
```

Then in my control repo, at the same location as the Puppetfile , is executed the following commands:

``/usr/local/bin/pdk bundle install``
``/usr/local/bin/pdk bundle exec rake r10k:syntax``
``~/.pdk/cache/ruby/2.1.0/gems/r10k-2.1.0/bin/r10k puppetfile install``

The two first commands work fine, but the last one return the following error:

```
/cadappl/ruby/2.3.4.a/ruby/lib/ruby/2.3.4/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- r10k/cli (LoadError)
	from /cadappl/ruby/2.3.4.a/ruby/lib/ruby/2.3.4/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/sa-jenkins-dca/.pdk/cache/ruby/2.1.0/gems/r10k-2.1.0/bin/r10k:3:in `<main>'
```

And also it seems that any command that is executed with R10K cause the same error.

The OS is RedHat 6 and the PDK is 1.5.0. I don't know if it is relevant, but the user that is executing these commands is not root, but the PDK don't need sudo permissions.

I couldn't find a reason for this error to happen. Any idea on how to solve it?

Thanks

**Comment by danielserrao** [comment]
That solved the problem, thanks DavidS.

**Comment by DavidS** [comment]
Thanks for reporting back!
