### ISSUE TITLE
pdk disable lint check for 140chars

### ISSUE THREAD

**Issue by ardrigh** [puppetlabs/pdk#538]
I am trying to disable the 140chars check in puppet-lint when running PDK. 
http://puppet-lint.com/checks/140chars/

I have updated the .sync.yml file to add the `disable_140chars` line to the Rakefile after running `pdk update` When I run `pdk validate` I am still getting warnings about lines longer than 140chars.

```shell
require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-syntax/tasks/puppet-syntax'
require 'puppet_blacksmith/rake_tasks' if Bundler.rubygems.find_name('puppet-blacksmith').any?

PuppetLint.configuration.send('disable_relative')
PuppetLint.configuration.send('disable_140chars')
```
```shell
warning: puppet-lint: manifests/postgresql_database.pp:40:140: line has more than 140 characters
```

PDK appears to be ignoring the lines in the Rakefile for which checks to run.

Is there some other way I should define this check to be disabled?

**Comment by dan-wittenberg** [comment]
Can you add to the end of the line some code to ignore?   #lint:ignore:140chars

**Comment by jarretlavallee** [comment]
Configuring the Rakefile will disable the checks for any rake tasks, but `pdk validate` calls the executable. Please try to configure a [.puppet-lint](https://github.com/rodjek/puppet-lint#configuration-file) file in the module root to disable the checks for the whole module with `pdk validate` or use control comments in the code as Dan mentioned.

**Comment by ardrigh** [comment]
Thanks I will add the `.puppet-lint.rc` file to disable the check.

**Comment by sirinek** [comment]
Is there a ticket currently open for this? I am running into the same issue. If the solution is to use the .puppet-lint.rc file, then okay, but the template file (and likely, documenttion) needs to be updated to reflect this.

**Comment by scotje** [comment]
Yes, one of the goals for `pdk config` is to reduce the need for users to modify the template repo itself.

**Comment by rodjek** [comment]
As of PDK 1.9.0, we now generate a `.puppet-lint.rc` for you using the same values that `.sync.yml` uses to generate the `Rakefile`. Eventually `pdk config` will handle this scenario but at least for now the behaviour of `pdk validate` and `bundle exec rake lint` is consistent.

**Comment by ardrigh** [comment]
Thanks for adding this.

I had done some pdk updates with 1.9.1 and noticed a change to `.puppet-lint.rc` but I hadn't had time to look at it.
