### ISSUE TITLE
PDK convert/update should process moduleroot_init templates if they don't already exist

### ISSUE THREAD

**Issue by nabertrand** [puppetlabs/pdk#547]
PDK moduleroot_init templates are only added to a module during creation (pdk new). There is currently no mechanism to get these templates added to an existing module. Perhaps they could be processed and added during convert/update if they don't already exist in the module? A simpler, less elegant solution would be to just add an 'init' flag to update/convert. See https://github.com/nabertrand/pdk/pull/1 for an example.

**Comment by scotje** [comment]
It definitely seems like `pdk convert` at least should do this, we will investigate.

**Comment by rodjek** [comment]
Tracking in JIRA at https://tickets.puppetlabs.com/browse/PDK-1363
