### ISSUE TITLE
class params feature in class object template not documented or useable

### ISSUE THREAD

**Issue by term1n4l** [puppetlabs/pdk#557]
**Describe the bug**
The class object template has a 'params' option that seems to be missing from documentation. I have tried working out how to pass values to this params option so I can create class params at 'pdk new class' but have so far been unable to do so.

**To Reproduce**
'pdk new class <classname>('type param, type param1')' or 'pdk new class <classname> "type param, type param1"' or 'pdk new class <classname> params=['type param','type param1']' none of these work to pass the param to the class template object.

**Expected behavior**
Either to be able to create said params as documented in the class object, or to be advised when this feature will be available.

**Additional context**
- PDK 1.6.1, Puppet 5.5.3

> Class.erb:
> `<%- if params -%>`
> `#`
> `<%-   params.each do |param| -%>`
> `# @param <%= param[:name] %> A description of this parameter.`
> `<%-   end -%>`
> `class <%= name %>(`
> `<%-   params.each do |param| -%>`
> `   <%= param[:type].ljust(max_type_length) %> $<%= param[:name] %>,`
> `<%-   end -%>`
> `) {`
> `<%- else -%>`
> `  class <%= name %> {`
> `<%- end -%>`
> `}`

**Comment by rodjek** [comment]
The functionality to specify parameters was removed during the beta before PDK was released as it was found during usability testing to be generally confusing to use and consumed more time than it saved. At this time there is no plan to make this feature available.

If this functionality is something that you and other PDK users would like to see in the future, I'd recommend starting a discussion in the [pdk-planning repo](https://github.com/puppetlabs/pdk-planning) and we can work on the design together.
