### ISSUE TITLE
pdk update 

### ISSUE THREAD

**Issue by robertlabrie** [puppetlabs/pdk#567]
**Describe the bug**

running `pdk update` on a project where I'd removed Gemfile* hangs. Running `ps aux` reveals:

Your user account isn't allowed to install to the system RubyGems.\012  You can cancel this installation and run:\012\012      bundle install --path vendor/bundle\012\012  to install the gems into ./vendor/bundle/, or you can enter your password\012  and install the bundled gems to RubyGems using sudo.\012\012  Password:  true

**To Reproduce**
Run `pdk convert`. Work on the project for a few days. Play with the gemfile, decide you hate it, delete it, create a new one by running `pdk update`.

**Expected behavior**
Bundle install works

**Additional context**
- Your PDK installation method (native packages or via Rubygems): `brew cask install puppetlabs/puppet/pdk`
- Your PDK version (`pdk --version`) 1.7.0
- Your operating system / platform MacOS 10.12.6

**Comment by rodjek** [comment]
Hi @robertlabrie, sorry about the delay in getting back to you regarding this. I'm unable to reproduce this issue locally. Are you still able to reproduce this problem on your end using the latest version of PDK? If so, can you try to create a small example repository that demonstrates the problem?
