### ISSUE TITLE
pdk test unit --parallel fails

### ISSUE THREAD

**Issue by marcelloromani** [puppetlabs/pdk#569]
**Describe the bug**
As mentioned in #446, `--parallel` is an experimental feature that should run unit tests using multiple threads
I tried it via:
```
pdk test unit --parallel
```
And I got the following error:
```
pdk (WARN): This module is compatible with an older version of PDK. Run `pdk update` to update it to your version of PDK.
pdk (INFO): Using Ruby 2.4.4
pdk (INFO): Using Puppet 5.5.3
[✔] Preparing to run the unit tests.
[✖] Running unit tests in parallel.
pdk (FATAL): Unit test output did not contain a valid JSON result: 
```

**To Reproduce**
```
pdk test unit --parallel
```

**Expected behavior**
Unit tests should be executed and yield the same results as
```
pdk test unit
```

**Additional context**
`pdk --version`: `1.7.0`
pdk Ruby: 2.4.4
pdk Puppet: 5.5.3
OS: Mac OS High Sierra 10.13.6

**Comment by scotje** [comment]
@marcelloromani is there any additional output after `pdk (FATAL): Unit test output did not contain a valid JSON result:`?

Can you try running `pdk test unit --parallel --debug` and paste the complete output here?

**Comment by rodjek** [comment]
I'm going to close out this issue due to lack of activity. Please feel free to reopen it if you're still experiencing this problem.

**Comment by marcelloromani** [comment]
Apologies @scotje I haven't had a chance to work on that anymore due to changes in job commitments.
