### ISSUE TITLE
Can't install in Fedora 29

### ISSUE THREAD

**Issue by roman-pomyanskiy** [puppetlabs/pdk#582]
**Describe the bug**
rpm package for fc27 can't install in fc29.

**To Reproduce**
In Fedora 29
wget https://pm.puppet.com/cgi-bin/pdk_download.cgi?arch=x86_64&dist=fedora&rel=27&ver=latest
dnf install ./pdk-1.7.1.0-1.fc27.x86_64.rpm
Last metadata expiration check: 0:51:41 ago on Thu 25 Oct 2018 10:12:14 AM +04.
Error: 
 Problem: conflicting requests
  - nothing provides /bin/mkdir needed by pdk-1.7.1.0-1.fc27.x86_64

**Expected behavior**
Installed PDK

**Additional context**
- lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 29 (Twenty Nine)
Release:	29
Codename:	TwentyNine

- dnf --version
4.0.4
  Installed: dnf-0:4.0.4-1.fc29.noarch at Tue 16 Oct 2018 05:39:01 AM GMT
  Built    : Fedora Project at Mon 15 Oct 2018 12:00:52 PM GMT

  Installed: rpm-0:4.14.2-1.fc29.x86_64 at Thu 27 Sep 2018 04:44:19 PM GMT
  Built    : Fedora Project at Wed 22 Aug 2018 08:07:47 AM GMT
- ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

**Comment by ardrigh** [comment]
Some additional information for the RPM maintainers - 

Fedora has a symlink for `/bin` to `/usr/bin` and the same for `/sbin` to `/usr/sbin`. It's might not be a good idea to rely on them. Using `/usr/bin/mkdir` should work the same as other distributions.

Fedora 29 also update PATH to prioritise local user binaries: https://fedoraproject.org/wiki/Releases/29/ChangeSet#User_PATH_Prioritization

**Comment by scotje** [comment]
Hi @ardrigh , I've update https://tickets.puppetlabs.com/browse/PDK-1050 to reflect the need to add support for Fedora 29 as well as more directly targeting packages at Fedora 28.

The Puppet Agent folks are currently in the process of adding the infrastructure necessary to build packages for Fedora 29 so once they have completed that work we should be able to build PDK packages on top of that pretty quickly.

**Comment by ardrigh** [comment]
Is there any update on the new Fedora packages?

**Comment by ardrigh** [comment]
There are Puppet Agent packages available for Fedora 28. 

Hopefully someone include a fix for "nothing provides /bin/mkdir needed by pdk" in a Fedora 28 package while Fedora 29 package is being added.

**Comment by scotje** [comment]
@ardrigh @roman-pomyanskiy We should have the build infrastructure in place now for f28 and f29 packages. I'm working on adding those platforms to the PDK build pipeline today.

**Comment by ardrigh** [comment]
@scotje thank you, very much appreciated!

**Comment by scotje** [comment]
fc28 and fc29 were merged into the PDK packaging configuration here: https://github.com/puppetlabs/pdk-vanagon/pull/181

The next release of PDK (currently scheduled for the week of Jan 23) will include packages for both.

**Comment by ardrigh** [comment]
@scotje any updates on when the PDK new release will be available? I have been holding out hoping it would be out by now.

**Comment by scotje** [comment]
@ardrigh We were waiting for the Puppet 6.2.0 release (which came out today) so that we could bundle it into the packages. Current plan is for PDK release to go out on Monday 1/28.

**Comment by scotje** [comment]
@ardrigh @roman-pomyanskiy PDK 1.9.0, including Fedora 29 packages is now available at https://puppet.com/download-puppet-development-kit
