### ISSUE TITLE
Pdk validate should not assume that all puppet: URL require 'modules/'.

### ISSUE THREAD

**Issue by KedneckInc** [puppetlabs/pdk#591]
**Describe the bug**

When running `pdk validate -a`  it assumes that any `puppet:///name` URL is missing the 'modules/' and _corrects_ it to `puppet://modules/name`.  This is an erroneous assumption made without full information, since development may occur on a system where puppet master is not installed.  Pdk cannot know that 'module/' is required in all cases.

**To Reproduce**
Have a `puppet:///name` URL in your code, and run `puppet validate -a` on it.

**Expected behavior**
The `puppet:///name` URL should remain unchanged.

**Additional context**
PDK Version: 1.7.0
OS: CentOS 7, and/or RedHat Enterprise 7.5

**Comment by scotje** [comment]
Hello and thanks for using the PDK!

The check in question is implemented by `puppet-lint` (http://puppet-lint.com/checks/puppet_url_without_modules/). We are working on making in easier to customize the application of `puppet-lint` rules directly via the PDK, but for the time being, you can use a `.puppet-lint.rc` file to customize how rules are applied in your module:

https://github.com/rodjek/puppet-lint#configuration-file

Please let me know if you have any questions or if that doesn't work for you for any reason.

**Comment by KedneckInc** [comment]
Sorry I took so long.  Worked fine with the configuration entry.  Many thanks!
