### ISSUE TITLE
pdk expects missing git binaries

### ISSUE THREAD

**Issue by pizzaops** [puppetlabs/pdk#61]
Currently the `pdk` expects `git` to exist at `/opt/puppetlabs/sdk/private/git/bin/git`. However, we install the `pdk` via `gem install pdk` which of course does not install git or create anything inside `/opt/puppetlabs`.

Users can just symlink git to that location but if there's a "correct" way to handle that, I'd love to document it.

Maybe a reasonable solution might be to allow it to search the normal $PATH for `git` when installed as a Gem instead of as part of the official `pdk` packaging (which doesn't yet exist).

**Comment by scotje** [comment]
David's open PR (https://github.com/puppetlabs/pdk/pull/58) adds the system path fallback, in the meantime you can set the `PDK_USE_SYSTEM_BINARIES` environment variable as described here: https://github.com/puppetlabs/pdk#contributing
