### ISSUE TITLE
pdk build should fix file + directory rights for tar file

### ISSUE THREAD

**Issue by mcgege** [puppetlabs/pdk#618]
**Describe the bug**
`pdk build` creates a tar file based on the current file rights in my repository. I'm working with a umask of `0027`, so `other` has no access on the files and directories and these rights will be stored in the tar file as is. If you use `r10k` (and probably also in other configurations) this can cause problems, e.g. [here](https://github.com/dev-sec/puppet-os-hardening/issues/175).

**To Reproduce**
1. Create a new file in your module directory with file rights `0640`
2. Build your module package with `pdk build`
3. Examine the tar file (`tar -xvf pkg/...`)

**Expected behavior**
PDK should adjust the file and directory rights when running `pdk build`, so that `group` and `other` can access them.

**Additional context**
- Your PDK installation method (native packages or via Rubygems)
   - native package
- Your PDK version (`pdk --version`)
   - 1.8.0
- Your operating system / platform
   - OpenSUSE 15.0

**Comment by rodjek** [comment]
Thanks @mcgege, I've created https://tickets.puppetlabs.com/browse/PDK-1309 to track this issue

**Comment by rodjek** [comment]
Fixed in #713
