### ISSUE TITLE
PDK and beaker

### ISSUE THREAD

**Issue by jocelynthode** [puppetlabs/pdk#622]
Hey,

I'm trying to setup acceptance tests on a puppet module create via PDK 1.9. Looking at the puppetlabs repo (e.g.: https://github.com/puppetlabs/puppetlabs-ntp/tree/master/spec) I see that they all have the same structure with an acceptance helper and a spec/acceptance folder containing a nodeset.

However I cannot find a documentation on how to generate these files and a default configuration for a fresh PDK project. 

Could someone please point me in the right direction ?

**Comment by scotje** [comment]
PDK does not currently "officially" support an acceptance testing workflow. (See https://github.com/puppetlabs/pdk-planning/issues/27 for the existing feature request.)

That said, if you are new to module acceptance testing, we would strongly suggest you take a look at Litmus which is a new framework for acceptance test provisioning etc.

There is a nice tutorial on how to convert a module to use Litmus here https://github.com/puppetlabs/puppet_litmus/wiki/Converting-a-module-to-use-Litmus

**Comment by jocelynthode** [comment]
Hey @scotje,

Thanks I never heard of litmus before, but the documentation looks way
better.

I was able to make beaker work however, now I'm wondering is beaker dead
and should people now start using litmus or will these two coexist?

What are the main differences?


Le jeu. 16 mai 2019 à 01:49, Jesse Scott <notifications@github.com> a
écrit :

**Comment by scotje** [comment]
The main difference as I understand it is a separation of responsibilities, with Litmus focusing mostly on provisioning and letting you use your preferred test harness (serverspec, etc.).

For basic module acceptance testing, I think Litmus is the future, but there are no immediate plans to discontinue beaker as it still supports more complex test scenarios with lots of interacting hosts. (Litmus may support those more complex setups in the future.)

**Comment by scotje** [comment]
Please let us know if you have any other questions.
