### ISSUE TITLE
PDK Validate error in psych in 1.9.0

### ISSUE THREAD

**Issue by ghost** [puppetlabs/pdk#623]
**Describe the bug**
```pdk validate``` fails with /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/class_loader.rb:97:in `find': Tried to load unspecified class: Symbol
 (Psych::DisallowedClass)
see https://github.com/watir/watir/issues/790
<details>
<summary>Commandline Output</summary>
pdk (INFO): Using Puppet 5.5.8
[✔] Installing missing Gemfile dependencies.
[✔] Checking metadata syntax (metadata.json tasks/*.json).
[✔] Checking module metadata style (metadata.json).
[|] Checking YAML syntax (["**/*.yaml", "*.yaml", "**/*.yml", "*.yml"])./opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/class_loader.rb:97:in `find': Tried to load unspecified class: Symbol
 (Psych::DisallowedClass)
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/class_loader.rb:28:in `load'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/class_loader.rb:39:in `block (2 levels) in <class:ClassLoader>'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/class_loader.rb:32:in `symbolize'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/class_loader.rb:82:in `symbolize'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/scalar_scanner.rb:84:in `tokenize'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:60:in `deserialize'

        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Scalar'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:337:in `block in revive_hash'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each_slice'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/2.4.0/psych.rb:302:in `safe_load'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/lib/pdk/validate/yaml/syntax.rb:78:in `block in invoke'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/lib/pdk/validate/yaml/syntax.rb:64:in `each'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/lib/pdk/validate/yaml/syntax.rb:64:in `invoke'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/lib/pdk/validate/yaml_validator.rb:23:in `block in invoke'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/lib/pdk/validate/yaml_validator.rb:22:in `each'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/lib/pdk/validate/yaml_validator.rb:22:in `invoke'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/lib/pdk/cli/validate.rb:112:in `block (3 levels) in <module:CLI>'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/lib/pdk/cli/validate.rb:111:in `each'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/lib/pdk/cli/validate.rb:111:in `block (2 levels) in <module:CLI>'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/lib/pdk/cli.rb:18:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.9.0/exe/pdk:6:in `<top (required)>'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/bin/pdk:23:in `load'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/bin/pdk:23:in `<main>'
</details>

**To Reproduce**
The simplest sequence of steps you have discovered which triggers the bug.
```pdk validate```
**Expected behavior**

**Additional context**
- Your PDK installation method (native packages or via Rubygems)
  - (If via Rubygems, please include your Ruby version `ruby -v`)
- Your PDK version (`pdk --version`) 1.9.0
- Your operating system / platform 4.18.0-14-generic #15-Ubuntu SMP Mon Jan 14 09:01:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rodjek** [comment]
Thanks @gleichdavid, this is a known issue that is being tracked in https://tickets.puppetlabs.com/browse/PDK-1273

**Comment by rodjek** [comment]
The fix for this issue was released in PDK 1.9.1
