### ISSUE TITLE
requirements for metadata.json does not match actual requirements

### ISSUE THREAD

**Issue by ripienaar** [puppetlabs/pdk#634]
**Describe the bug**
The latest metadata.json documentation is in https://puppet.com/docs/puppet/6.3/modules_metadata.html it states which fields are required and which are optional.  For example operatingsystem_support is an optional field.

pdk build however refuse to build this perfectly valid module and will not accept a empty list either.

**To Reproduce**
Remove operatingsystem_support from metadata.json, try to build

**Expected behavior**
Modules written according to official specification can be built.

**Additional context**
PDK 1.9.0, EL7, rpm install

**Comment by rodjek** [comment]
`pdk build` currently enforces this (and some other) optional metadata fields in the expectation of the built module being uploaded to the forge where these fields are used. From the looks of the linked issue it looks like you're building the packages and then distributing them by another means? This is not a use case we considered when planning out `pdk build` so I just want to make sure I have the details of your use case correct.

**Comment by ripienaar** [comment]
We are distributing it via the forge, the modules are perfectly valid as per Puppet specification and forge accepts them @rodjek - pdk refuses to build perfectly fine and acceptable modules :)

**Comment by ripienaar** [comment]
Example, perfectly valid module https://forge.puppet.com/choria/mcollective_agent_puppet pdk refuses to build it

**Comment by rodjek** [comment]
Thanks @ripienaar, I've opened https://tickets.puppetlabs.com/browse/PDK-1310 to track this.
