### ISSUE TITLE
specifying the environment variable PUPPET_GEM_VERSION does not work

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk#635]
**Describe the bug**
The Gemfile allows for specifying the puppet version with the environment variable `PUPPET_GEM_VERSION`. When this is done, errors happens where I would expect no errors and for PDK to use the version specified.

**To Reproduce**
```sh
export PUPPET_GEM_VERSION=6.3.0
pdk validate
```

**Expected behavior**
For PDK to use Puppet 6.3.0 and for the tests to succeed.

**Additional context**
- Your PDK installation method: native packages

- Your PDK version: 1.9.0
- Your operating system / platform: MacOS Mojave

**Comment by rodjek** [comment]
`PUPPET_GEM_VERSION` is not part of the PDK "public API". It remains in the puppetlabs/pdk-templates `Gemfile` template for compatibility with existing CI setups that call the rake tasks from puppetlabs_spec_helper. The correct way to specify the Puppet version with PDK commands is the `--puppet-version` or `--pe-version` flags - https://puppet.com/docs/pdk/1.x/pdk_reference.html#pdk-validate-command.

**Comment by ghoneycutt** [comment]
Thanks for explaining how to achieve this! Please re-open though as specifying this environment variable should not cause pdk to not work. Would expect that pdk would ignore it and continue on or at document that specifying this will break things.

**Comment by scotje** [comment]
@ghoneycutt can you clarify what errors you are receiving in this situation? PDK should be ignoring the exported value of `PUPPET_GEM_VERSION` as it carefully manages the execution environment of it's subprocesses.

**Comment by ghoneycutt** [comment]
I'm not able to reproduce using PDK 1.9.1

**Comment by ghoneycutt** [comment]
This makes adoption hard as I normally export that variable with the current work flow that uses rvm and bundler. When migrating to PDK I have to remember to unset it. A better user experience would be PDK telling me that it is set and that it shouldn't be and that it's going to ignore it and tell me to use `--puppet-version` or `--pe-version` to specify the version.

**Comment by rodjek** [comment]
Fixed in #671
