### ISSUE TITLE
pdk update modifies the metadata.json such that it is missing a newline on the final line

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk#636]
**Describe the bug**
When using `pdk update` the resulting `metadata.json` is missing a newline at the end of the file. 

Here's an example.

https://github.com/ghoneycutt/puppet-module-rpcbind/pull/40/files#diff-490694a9db8f7a371538da1abe484314R77

**To Reproduce**
Run `pdk update` on a module.

**Expected behavior**
There is a new line character.

**Additional context**
- Your PDK installation method: native packages
- Your PDK version: 1.9.0
- Your operating system / platform: macos mojave

**Comment by scotje** [comment]
Tracked in JIRA as https://tickets.puppetlabs.com/browse/PDK-1308

**Comment by scotje** [comment]
Resolved by #640

**Comment by ghoneycutt** [comment]
Thanks @scotje and @rodjek
