### ISSUE TITLE
template-ref behaviour in PDK 1.10.0 breaks backwards compatibility

### ISSUE THREAD

**Issue by term1n4l** [puppetlabs/pdk#661]
template ref value being included in the template-url in metadata.json breaks backwards compatibility with previous versions of the PDK and older PDK versions module metadata is incompatible with the latest PDK

Try a `pdk update` from previous version of the PDK after creating a module in 1.10.0 where the template url and template ref (currently required) is specified.
Try running a `pdk update` from PDK 1.10.0 in a module created in a version prior to 1.10.0 and note that the template ref value is using the PDK version as the default reference value instead of the previous behaviour of using and updating the 'template-ref' value in metadata.json.

The template ref value should be utilised and updated via the 'template-ref' value already in metadata.json rather than being tacked onto the end of the template URL/URI.

**Additional context**
Native packages for Windows and Linux.
- Your PDK version (`pdk --version`)
1.10.0, 1.9.1
- Your operating system / platform
Fedora 30 (using the Fedora 29 puppet 5 repo) and Windows 10 1809.

**Comment by scotje** [comment]
> Try a `pdk update` from previous version of the PDK after creating a module in 1.10.0 where the template url and template ref (currently required) is specified.

Can you elaborate on what behavior you would expect and what you are observing in this case?

Previous to PDK 1.10.0 there wasn't really a way to specify that you wanted to track anything other than `master` in a custom template repo. All `template-ref` in `metadata.json` tracks is what the last revision applied to the repo is, in PDK prior to 1.10.0 it did not impact future invocations of `pdk update` which always just looked at `master` if you were using a custom template repo.

> Try running a `pdk update` from PDK 1.10.0 in a module created in a version prior to 1.10.0 and note that the template ref value is using the PDK version as the default reference value instead of the previous behaviour of using and updating the 'template-ref' value in metadata.json.

This is indeed a bug that has been reported here https://github.com/puppetlabs/pdk/issues/659

You should be able to workaround that issue on PDK 1.10.0 by invoking `pdk update --template-ref=master` (or whatever your desired branch/tag is) once on the module. After that PDK will remember the desired branch for future invocations of `pdk update`.

**Comment by term1n4l** [comment]
> > Try a `pdk update` from previous version of the PDK after creating a module in 1.10.0 where the template url and template ref (currently required) is specified.
> 
> Can you elaborate on what behavior you would expect and what you are observing in this case?

Expected behaviour: being able to apply any template updates to the module using any version of the PDK.
Observed behaviour: error about the template url being malformed (due to the tag on the end of the template url). This also happens if you run `pdk new class <classname>` within the module.
 
> > Try running a `pdk update` from PDK 1.10.0 in a module created in a version prior to 1.10.0 and note that the template ref value is using the PDK version as the default reference value instead of the previous behaviour of using and updating the 'template-ref' value in metadata.json.
> 
> This is indeed a bug that has been reported here #659
> 
> You should be able to workaround that issue on PDK 1.10.0 by invoking `pdk update --template-ref=master` (or whatever your desired branch/tag is) once on the module. After that PDK will remember the desired branch for future invocations of `pdk update`.

I understand part of what I describe here is a known bug and already reported, however the behaviour I'm describing here is that any older modules that you try to run `pdk update` on will break in 1.10.0  because of either the way the template url is specified (e.g. if using the old scp method), or because the template ref is not recognised and it defaults to using the PDK version as a result (when using an acceptable format for the URI/URL.

**Comment by scotje** [comment]
Thank you for the additional context. 

After discussing this internally, we are going to adopt a policy that modules that have been `pdk update`-ed to the latest PDK release should also still be compatible with the previous release. That is something we didn't do in this case and I apologize for the inconvenience this has caused you and your team.

For this particular issue, the cat is kind of out of the bag and we can't really retroactively implement a fix that wouldn't require some upgrading to be done anyway, so I think in this case our recommendation would be for you to encourage the other members of your team to upgrade to the latest version of PDK. Please let us know if there is some issue preventing them from being able to do so.

**Comment by term1n4l** [comment]
We have decided to migrate our codebase to the newer version moving forward.
