### ISSUE TITLE
create_process error on windows when creating a new module

### ISSUE THREAD

**Issue by TraGicCode** [puppetlabs/pdk#73]
When trying to create a new module using the PDK on windows i recieve the following error

![image](https://user-images.githubusercontent.com/6224270/27008136-8d292b30-4e2f-11e7-9b89-7f83e594caa5.png)

**Comment by DavidS** [comment]
The defaults require git on the system path to access the template. Alternatively you can specify a `--template-url` pointing to a local directory (e.g. a checkout of http://github.com/puppetlabs/pdk-module-template) to avoid this.

The error message has already been improved on master (https://github.com/puppetlabs/pdk/blob/master/lib/pdk/cli/exec.rb#L40), but not yet pushed to rubygems.

**Comment by DavidS** [comment]
Michael, I also added a note to the README (see above). I hope that'll help newcomers in the future.

**Comment by TraGicCode** [comment]
I did indeed have both git and bundler within my system path.  It's possible i didnt have your codebase with the system path fallback yet.  I was using the gem which might not be up-to-date.  I'll give this a shot using the git repo tommorow! Thanks
