### ISSUE TITLE
PDK's puppet 5 doesn't come with any augeas lenses

### ISSUE THREAD

**Issue by igalic** [puppetlabs/pdk#743]
PDK 1.12.0 comes with 3 different puppet versions: 4.x, 5.x and 6.x
Two of these Puppet versions have an `augeas` provider built-in, however, there are no lenses distributed with PDK.

**To Reproduce**

```puppet
augeas { 'activate gpgcheck':
    incl    => '/etc/yum.conf',
    lens    => 'Yum.lns',
    context => '/files/etc/yum.conf/main/',
    changes => 'set gpgcheck 1',
}
```

Trying to apply this will result in puppet complaining that,

```
Warning: Augeas[activate gpgcheck](provider=augeas): Loading failed for one or more files, see debug for /augeas//error output
Debug: Augeas[activate gpgcheck](provider=augeas): /augeas/load/Xfm/error = Can not find Yum.lns
```

a quick check into the RPM reveals that this is sadly true:

```shell-session
% rpm -ql pdk | grep "\.aug"
```
 
**Expected behavior**

I'd much rather this worked…

**Additional context**
- Your PDK installation method: rpm
- Your PDK version: 1.12.0
- Your operating system / platform: Red Hat Enterprise Linux 7.6.

**Comment by igalic** [comment]
now, to use `strace`, to find out where the lenses are expected.

**Comment by scotje** [comment]
Yeah, we have been trying to reduce the package file count as much as possible but it's probably worth keeping the lenses around, they aren't that big:

https://github.com/puppetlabs/pdk-vanagon/blob/master/configs/components/pdk-runtime.rb#L30

**Comment by igalic** [comment]
augeas lenses are still being deleted: https://github.com/puppetlabs/pdk-vanagon/blob/main/configs/components/pdk-runtime.rb#L45

**Comment by chelnak** [comment]
@igalic I'm going to look in to this

**Comment by gavindidrichsen** [comment]
Fixed in latest version
