### ISSUE TITLE
better way to find gem path

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk#744]
I saw this in the codebase and thought the following code might be better.  However, I don't really know what is supposed to be retruned.

```


Gem::Specification.latest_specs.find {|spec| spec.name.eql?('bundler') }.base_dir
=> "/opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0"

```

```
# This allows the subprocess to find the 'bundler' gem, which isn't
# in GEM_HOME for gem installs.
# TODO: There must be a better way to do this than shelling out to
# gem... Perhaps can be replaced with "Gem.path"?
 [File.absolute_path(File.join(`gem which bundler`, '..', '..', '..', '..'))]
```

https://github.com/puppetlabs/pdk/blob/master/lib/pdk/util/ruby_version.rb#L105

**Comment by logicminds** [comment]
Also `Gem.paths.home => "/opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0"`

**Comment by scotje** [comment]
Thanks for the suggestions @logicminds!

`Gem.paths.home` won't work unfortunately, as the comment states, `bundler` lives outside of `GEM_HOME`. However the specifications method may work.

I'll try it locally and see if all the tests are still happy, there are some funny edge cases if I recall correctly from working on this before.
