### ISSUE TITLE
--pe-version fails for gem-based installation in air gapped environment

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk#761]
**Describe the bug**
When I use pdk validate --pe-version=2018.1, pdk will try and reach out to the internet and grab a list of pe versions.  (https://github.com/puppetlabs/pdk/blob/master/lib/pdk/util/puppet_version.rb#L19)

Because I am working on a system without internet this fails because I am unable to download the associated pe versions map.

**To Reproduce**
1. Turn internet off
2. pdk validate --pe-version=2018.1

**Expected behavior**
Pdk should use an internal map of the pe versions in order to find the associated puppet gem version.  PE doesn't change all that much so it should keep a cached version inside the gemfile.  An alternative approach is to distribute the pe map in the pdk-templates.

**Comment by scotje** [comment]
It is currently cached as part of the packaged installation but we can look into integrating a cached copy of the file into the `gem` build process as well.
