### ISSUE TITLE
in_module_root? gives false positive

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk#768]
**Describe the bug**
The [in_module_root?](https://github.com/puppetlabs/pdk/blob/master/lib/pdk/util.rb#L150) function reports true whenever a lib directory is found.  It uses 
the following [folders](https://github.com/puppetlabs/pdk/blob/master/lib/pdk/util.rb#L10) to determine if the current directory is indeed a module.

However, just because a folder has a lib directory, does not mean it is a module and does not also mean it has a Gemfile either. 

**To Reproduce**
1. Create a directory `mkdir -p /tmp/test/lib`
2. cd /tmp/test
3. run `pdk console` or possible any other pdk command

**Expected behavior**
PDK should return the correct boolean value when the current directory is not a module.

This might mean that instead of looking for lib, we look for lib/puppet.

**Additional context**
```
pdk console
pdk (WARN): Module fixtures not found, please run pdk bundle exec rake spec_prep.
pdk (WARN): Unable to determine Puppet version for module: no metadata.json present in module.
/opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler.rb:431:in `initialize': no implicit conversion of nil into String (TypeError)
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler.rb:431:in `open'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler.rb:431:in `block in read_file'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/shared_helpers.rb:119:in `filesystem_access'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler.rb:430:in `read_file'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.14.0.pre/lib/pdk/cli/console.rb:75:in `gem_in_bundle_lockfile?'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.14.0.pre/lib/pdk/cli/console.rb:125:in `run_in_module'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.14.0.pre/lib/pdk/cli/console.rb:45:in `block (2 levels) in <module:CLI>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.14.0.pre/lib/pdk/cli.rb:56:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.14.0.pre/exe/pdk:6:in `<top (required)>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/bin/pdk:23:in `load'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/bin/pdk:23:in `<main>'
```

**Comment by rodjek** [comment]
`PDK::Util.in_module_root?` is deliberately pretty tolerant as it needs to try to determine if you're inside an unconverted module. I would suggest adding `PDK::CLI::Util.module_version_check` after `PDK::CLI::Util.ensure_in_module!` which will perform a further validation based on the module metadata and in this case cause the command to exit early saying that the module is not PDK compatible due to the missing metadata.json.

**Comment by glennsarti** [comment]
Yup, this tripped me up before 😢

**Comment by logicminds** [comment]
Wouldn't `lib/puppet` or `lib/facter` be a better directory to search for?

**Comment by glennsarti** [comment]
Good idea.

**Comment by rodjek** [comment]
:+1: to making the directory check more specific
