### ISSUE TITLE
Networking facts missing for RHEL7 and facter 2.x

### ISSUE THREAD

**Issue by overholw** [puppetlabs/pdk#776]
**Describe the bug**
In PDK 1.14 the network facts are missing for RHEL7 for all facter 2.x's (and 1.7).  They exist for RHEL6 and RHEL8.

**To Reproduce**
On RHEL7 with PDK 1.14 installed:
rpm -ql pdk | grep redhat-7-x86_64 | grep 'facts/2' | xargs grep network
returns no results.
Changing that to redhat-6-x86_64 or redhat-8-x86_64 returns 54 and 36 results respectively

**Expected behavior**
Expect there to be network facts for RHEL7 and facter 2.x.

**Additional context**
- We are using the PDK package from http://yum.puppetlabs.com/puppet5/el/7/x86_64/
- Your PDK version (`pdk --version`): 1.14.0
- Your operating system / platform: RHEL7 x86_64

We noticed this with facter 2.4 and PDK 1.13.  The network facts appeared to be there for other versions of facter 2.x in 1.13.
We are starting to test RHEL8 so need to upgrade from PDK 1.7 that does not have the facts for RHEL8.
I believe this is related to #694.

**Comment by scotje** [comment]
Hello @overholw, it looks like this issue has already been addressed in the upstream `facterdb` project (https://github.com/camptocamp/facterdb/commit/1bfc2fdaa3a16386e11a8f5d94e59acd2e7b58ef) but that hasn't made it into a released gem yet. Once they release a new version of the gem we will pick it up in the next PDK release (or you can manually update the module's bundle to get the new version).
