### ISSUE TITLE
"pdk validate" fails with "uninitialized constant PDK::VERSION (NameError)"

### ISSUE THREAD

**Issue by stevevdvkpe** [puppetlabs/pdk#786]
**Describe the bug**
When "pdk validate" is run it produces a Ruby traceback:

$ pdk validate
Traceback (most recent call last):
	8: from /home/stevev/.gem/ruby/2.5.0/bin/pdk:23:in `<main>'
	7: from /home/stevev/.gem/ruby/2.5.0/bin/pdk:23:in `load'
	6: from /home/stevev/.gem/ruby/2.5.0/gems/pdk-1.14.0/exe/pdk:6:in `<top (required)>'
	5: from /home/stevev/.gem/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/cli.rb:56:in `run'
	4: from /home/stevev/.gem/ruby/2.5.0/gems/cri-2.15.9/lib/cri/command.rb:314:in `run'
	3: from /home/stevev/.gem/ruby/2.5.0/gems/cri-2.15.9/lib/cri/command.rb:296:in `run'
	2: from /home/stevev/.gem/ruby/2.5.0/gems/cri-2.15.9/lib/cri/command.rb:360:in `run_this'
	1: from /home/stevev/.gem/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/cli/validate.rb:46:in `block (2 levels) in <module:CLI>'
/home/stevev/.gem/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/cli/util.rb:98:in `module_version_check': uninitialized constant PDK::VERSION (NameError)

Although I am a total Ruby-nuby, I was able to fix this by adding

require 'pdk/version'

to the top of pdk-1.14.0/lib/pdk/validate.rb, but I have no idea whether that is the best way to fix it.

**To Reproduce**
$ gem install --user-install pdk
$ cd (puppet module dir)
$ pdk validate

**Expected behavior**
As far as I know it should run validation tests?

**Additional context**
- Your PDK installation method (native packages or via Rubygems)
  gem install --user-install pdk
  - (If via Rubygems, please include your Ruby version `ruby -v`)
  $ ruby -v
  ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
- Your PDK version (`pdk --version`)
  $ pdk --version
  1.14.0
- Your operating system / platform
  Debian 10 (Buster)
  $ cat /etc/debian_version 
  10.1

**Comment by scotje** [comment]
I think this was probably already addressed by #778 but @rodjek can you confirm?

(See also: #775)

**Comment by stevevdvkpe** [comment]
Those certainly look quite relevant to my specific problem (especially #775).

**Comment by rodjek** [comment]
Yep, this has been resolved by #778
