### ISSUE TITLE
Add ability to autofix puppet manifests

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk#800]
There is already a `-a` flag for autofixing ruby files using rubocop.  However, there is not a similar flag or feature that also runs `puppet-lint -f` that auto fixes things as well. 

I should not have to revert to running `pdk bundle exec puppet-lint -f manifests/`

**Comment by natemccurdy** [comment]
@logicminds What version of the PDK are you using?

The PDK does have the ability to fix Puppet code with `pdk validate -a`: https://github.com/puppetlabs/pdk/blob/v1.14.1/lib/pdk/validate/puppet/puppet_lint.rb#L25


```
 ~/foo $ pdk validate -a
pdk (INFO): Running all available validators...
pdk (INFO): Using Ruby 2.5.7
pdk (INFO): Using Puppet 6.10.1
[✔] Checking metadata syntax (metadata.json tasks/*.json).
[✔] Checking module metadata style (metadata.json).
[✔] Checking YAML syntax (["**/*.yaml", "*.yaml", "**/*.yml", "*.yml"]).
[✔] Checking Puppet manifest syntax (**/*.pp).
[✔] Checking Puppet manifest style (**/*.pp).
[✔] Checking Puppet EPP syntax (**/*.epp).
[✔] Checking Ruby code style (**/**.rb).
corrected: puppet-lint: manifests/init.pp:25:22: double quoted string containing no variables
info: task-name: ./: Target does not contain any files to validate (tasks/**/*).
info: task-metadata-lint: ./: Target does not contain any files to validate (tasks/*.json).
```

**Comment by logicminds** [comment]
hmm, maybe I was doing it wrong.  I'll have to check again.

**Comment by logicminds** [comment]
This works now.  Closing
