### ISSUE TITLE
Generated descriptions for certain test comparisons break JUnit output

### ISSUE THREAD

**Issue by kenji-fukasawa** [puppetlabs/pdk#821]
Generated descriptions can cause the JSON parsing for JUnit output to fail.  When this occurs the created XML document will be empty.

### How to reproduce
Generate a new module with PDK.
```
$ pdk new module test-broken_junit
```

Create a unit test with the following content.
```
# ./spec/unit/broken_junit_spec.rb
# This test will break JUNIT output
RSpec.describe "broken-junit" do
  let(:large_nested_hash) do
    {
      single_one: 'single_one',
      single_two: 'single_two',
      single_three: 'single_three',
      single_four: 'single_four',
      single_five: 'single_five',
      nested: {
        nested_one: 'nested_one',
        nested_two: 'nested_two',
        nested_three: 'nested_three',
        nested_four: 'nested_four',
        nested_five: 'nested_five',
      },
    }
  end

  subject do
    large_nested_hash
  end

  it { is_expected.to be_a Hash }
  it { is_expected.to eq large_nested_hash }
end
```

Running the test should result in a success.
```
$ pdk test unit -v
pdk (INFO): Using Ruby 2.5.7
pdk (INFO): Using Puppet 6.11.0
[✔] Preparing to run the unit tests.
/opt/puppetlabs/pdk/private/ruby/2.5.7/bin/ruby -I/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rspec-core-3.9.0/lib:/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rspec-support-3.9.0/lib /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rspec-core-3.9.0/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb --format documentation

broken-junit
  is expected to be a kind of Hash
  is expected to eq {:nested=>{:nested_five=>"nested_five", :nested_four=>"nested_four", :nested_one=>"nested_one", :nest...>"single_four", :single_one=>"single_one", :single_three=>"single_three", :single_two=>"single_two"}

Finished in 0.00334 seconds (files took 0.17747 seconds to load)
2 examples, 0 failures
```

It is important to notice that the hash comparison test description output (`is expected to eq {:nested...`) has two opening curly braces (`{`) and only one closing curly brace (`}`).  The is an artifact of how the test descriptions are condensed for output.  This causes the processing for JUnit output to fail.

Running the test with the JUnit format specified should result in an empty document.
```
pdk (INFO): Using Ruby 2.5.7
pdk (INFO): Using Puppet 6.11.0
[✔] Preparing to run the unit tests.
[✔] Running unit tests.
<?xml version='1.0'?>
<testsuites/>
```

If you comment out enough of the `single_` lines to ensure that the output produces two closing curly braces (`}`) it will generate the XML as expected.

### Extra info
I dug through the `lib/pdk/tests/unit.rb` file and found that the output is processed by the `PDK::Util.find_first_json_in` method ([line 112](https://github.com/puppetlabs/pdk/blob/master/lib/pdk/tests/unit.rb#L112)).  I was able to confirm that the RSPEC command output JSON is valid.  So, I went ahead and chased that method into the `lib/pdk/util.rb` file.  [Line 219](https://github.com/puppetlabs/pdk/blob/master/lib/pdk/util.rb#L219) appears to be the culprit.  I was able to confirm that when that condition exists it does not properly capture the JSON output from the command.  Unfortunately, I don't have a fix to propose as I don't know the conditions that need to be satisfied with that REGEX.

**Comment by scotje** [comment]
Hi @kenji-fukasawa! Thanks for the bug report! It does indeed look like that unbalanced `{` throws off the JSON-finding regular expression. We'll try to get a fix for this into the January release.
