### ISSUE TITLE
Puppetfile Resolver can't detect version of Puppet from PDK using Visual Studio Code

### ISSUE THREAD

**Issue by awslovato** [puppetlabs/pdk#830]
**Describe the bug**
Editing the Puppetfile causes the Resolver to output erroneous messages saying it can't find a compatible version of Puppet

**To Reproduce**
modify the Puppetfile in anyway except comments.

**Expected behavior**
The Puppetfile Resolver should see the PDK Puppet version and generate no errors.

**Additional context**
- Windows 10 MSI
- PDK 1.15.0
- Windows 10
- Visual Studio Code 1.41.1

gist with Puppetfile:
https://gist.github.com/awslovato/6c5bc143a0ffbb051e1c60b5b44d99d4

gist with Problems output from Visual Studio Code:
https://gist.github.com/awslovato/ca1c8bfca2c516b5767b55dc72becd2c

**Comment by glennsarti** [comment]
Moved to https://github.com/lingua-pupuli/puppetfile-resolver/issues/6 and closing here.
