### ISSUE TITLE
'pdk new module' bundler error with PDK-1.16 on macOS 10.14

### ISSUE THREAD

**Issue by gerardkok** [puppetlabs/pdk#845]
**Describe the bug**
`pdk new module motd` results in a bundler error:
```
$ pdk new module motd
pdk (INFO): Creating new module: motd
...
Metadata will be generated based on this information, continue? Yes
pdk (INFO): Using the default template-url and template-ref.
pdk (FATAL): 
/opt/puppetlabs/pdk/private/ruby/2.5.7/bin/bundle:23:in `load': cannot load such file -- /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe/bundle (LoadError)
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/bin/bundle:23:in `<main>'

pdk (FATAL): Unable to resolve Gemfile dependencies.
```
The module is created, although I can't really tell if it's complete.

**To Reproduce**
Install PDK on macOS 10.14 from https://pm.puppet.com/cgi-bin/pdk_download.cgi?dist=osx&rel=10.14&arch=x86_64&ver=latest, and create a new module.

**Expected behavior**
It should not throw the error.

**Additional context**
- Your PDK installation method: installed from https://puppet.com/try-puppet/puppet-development-kit/.
- Your PDK version (`pdk --version`): 1.16.0
- Your operating system / platform: macOS 10.14.6

I think this is caused by some folders in /opt/puppetlabs/pdk/private/ruby not being world-readable after installation:
```
# find /opt/puppetlabs/pdk/private/ruby -type d ! -perm -o=r
/opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/bundler-1.17.2
/opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/bundler-1.17.2/exe
/opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-1.17.2
/opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe
```
If I fix the permissions like so:
```
# chmod -R a+rX /opt/puppetlabs/pdk/private/ruby/
```
then `pdk new module` runs correctly:
```
$ pdk new module motd
pdk (INFO): Creating new module: motd
...
Metadata will be generated based on this information, continue? Yes
pdk (INFO): Using the default template-url and template-ref.
pdk (INFO): Module 'motd' generated at path '/Users/gerard/vscode/motd'.
pdk (INFO): In your module directory, add classes with the 'pdk new class' command.
```
So it looks like these directories are installed with permissions that are too strict, at least if you use the package (I have not checked installing with homebrew, or one of the other packages).

**Comment by scotje** [comment]
Thanks for the report and diagnosis. We'll take a look at this and release a new build shortly if needed.

**Comment by scotje** [comment]
PDK 1.16.0.2, which addresses this issue, is now available. Sorry for the inconvenience and the delays in getting the new package out. We hit a couple speed bumps with our release tooling along the way.
