### ISSUE TITLE
json-schema is unmaintained and does not work with ruby 2.7

### ISSUE THREAD

**Issue by lelutin** [puppetlabs/pdk#848]
Hello,

I'm currently working on getting pdk packaged for debian. I was told that during the current dev sprint of the debian ruby team (working on transitioning debian testing to ruby 2.7), it was found that the json-schema library fails to build from source with ruby 2.7

Info about the failure can be found here:

https://people.debian.org/~kanashiro/ruby2.7/builds/7/ruby-json-schema/ruby-json-schema_2.8.1-1+rebuild1580878603_amd64-2020-02-05T04:56:44Z.build.txt

it was brought to my attention that the json-schema library has been unmaintained for a while now. this upstream ticket about trying to find new maintainers mentions some alternative libraries that can be used instead:

https://github.com/ruby-json-schema/json-schema/issues/423

So, for the future maintainability of pdk, it might be worthwhile to consider switching this library for another one offering similar functionality.

If the switch is done, it might affect #759  and maybe other issues regarding this dependency.

Cheers!

**Comment by glennsarti** [comment]
Thanks @lelutin .  We are aware that json-schema is no longer maintained and will be dropping that gem in PDK v2.0.0 e.g. (https://github.com/puppetlabs/pdk/commit/419dc518dabd8a7447d56da89b5439fb8b5bbdd3)

We weren't aware about the build failures though!

**Comment by lelutin** [comment]
@glennsarti great!

just out of curiosity, is there currently a planned or estimated date for release of pdk 2.0.0 ? I guess I'd rather wait for this version to come out before sending a package to debian.

**Comment by glennsarti** [comment]
Unfortunately I don't have a hard date for you.  It's currently As-Soon-As-Possible due to carrying Ruby 2.1.9 support and various other breaking things we want to get done.

Typically PDK is targeted at the same Ruby versions that Puppet Agent uses which is why we currently don't test on 2.6 or 2.7. Though that is not obvious in the PDK's gemspec.

@puppetlabs/pdk Any other thoughts?

**Comment by glennsarti** [comment]
Oh forgot to mention PDK planning is located in the [pdk-planning](https://github.com/puppetlabs/pdk-planning/projects) repo.

**Comment by lelutin** [comment]
> Unfortunately I don't have a hard date for you. It's currently As-Soon-As-Possible due to carrying Ruby 2.1.9 support and various other breaking things we want to get done.

ok, no problem. I'll keep my eyes open then.

> Typically PDK is targeted at the same Ruby versions that Puppet Agent uses which is why we currently don't test on 2.6 or 2.7. Though that is not obvious in the PDK's gemspec.

sure, this makes total sense!

thanks for that link for the milestones/planning!

**Comment by scotje** [comment]
Thanks @lelutin, please let us know if there is anything else to do for this right now, otherwise keep an eye out for the PDK 2.0.0 release. :)
