### ISSUE TITLE
Ruby error "cannot load such file" when running pdk 1.16 on macOS 10.15

### ISSUE THREAD

**Issue by XanderXAJ** [puppetlabs/pdk#850]
**Describe the bug**
When trying to run `pdk` (with or without arguments), I get the following error:

```
$ pdk
/opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubygems/core_ext/kernel_warn (LoadError)
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems.rb:1395:in `<top (required)>'
        from <internal:gem_prelude>:4:in `require'
        from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

It fails with the same error when trying to run a languageserver for Puppet 6.x (which uses Ruby 2.5) or Puppet 5.x (which uses Ruby 2.4 like `pdk`) using the official Puppet VS Code extension. Starting a languageserver for Puppet 4.x succeeds.

Sure enough, there doesn't seem to be a `kernel_warn.rb` file:

```
$ ll /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/2.5.0/rubygems/core_ext
total 24
-rw-r--r--  1 root  wheel  2567  1 Oct 12:02 kernel_gem.rb
-rw-r--r--  1 root  wheel  4139  1 Oct 12:02 kernel_require.rb

$ ll /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/2.4.0/rubygems/core_ext/
total 16
-rw-r--r--  1 root  wheel  2567  2 Oct 06:02 kernel_gem.rb
-rw-r--r--  1 root  wheel  4076  2 Oct 06:02 kernel_require.rb
```

**To Reproduce**
Install PDK using Brew, then run PDK:

```bash
brew cask install puppetlabs/puppet/pdk
# Create new terminal
pdk
```

**Expected behavior**

I would expect `pdk` to run or the languageserver to start successfully.

**Additional context**
PDK version 1.16.0.2 has been installed via Brew -- I can't run `pdk --version` as it also fails with the above error:

```
$ brew cask info pdk
pdk: 1.16.0.2
https://github.com/puppetlabs/pdk
/usr/local/Caskroom/pdk/1.16.0.2 (268.4MB)
From: https://github.com/puppetlabs/homebrew-puppet/blob/master/Casks/pdk.rb
```

Using macOS Catalina 10.15.3.

I previously had pdk 1.15 installed via Brew and this seemed to work OK. After upgrading, it no longer works. Uninstalling and reinstalling doesn't help.

There's suggestion that [this might be related to a bug in Rubygems 3.0.0](https://stackoverflow.com/a/53947252/5893392) and was fixed in Rubygems 3.0.1. However, I don't know much about Ruby and so I would by no means assume this is the issue. :)

**Comment by scotje** [comment]
I just validated that a clean install of 1.16.0.2 on macOS 10.15 seems to run OK. We have observed that `brew cask uninstall` sometimes does not completely remove everything, can you try the following sequence?

```
brew cask uninstall pdk
sudo rm -rf /opt/puppetlabs/pdk
brew cask install puppetlabs/puppet/pdk
```

The files should be located at the following paths, I suspect they are there but missing global read permissions, which the above sequence should correct.

```
$ find /opt/puppetlabs/pdk -name "kernel_warn.rb"
/opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_warn.rb
/opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/rubygems-update-3.0.0/lib/rubygems/core_ext/kernel_warn.rb
/opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb
/opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/rubygems-update-3.0.0/lib/rubygems/core_ext/kernel_warn.rb
```

**Comment by scotje** [comment]
P.S. we should have official macOS 10.15 packages with the next release.

**Comment by XanderXAJ** [comment]
Thanks for the confirmation. I've followed your instructions and things are now working. 👍 

`kernel_warn.rb` is present and correct, and looks like as you've posted above.

It might be worth investigating why uninstallation doesn't seem to fully uninstall the cask -- it seems like a reasonable guess that's where the issue came from.

With that said, I'm happy to close the ticket. Thank you for the help once again. 😄
