### ISSUE TITLE
`pdk` command errors out when ran from directory that has a Gemfile.lock

### ISSUE THREAD

**Issue by gerardkok** [puppetlabs/pdk#868]
**Describe the bug**
`pdk` ran from a directory that has a Gemfile.lock throws a Ruby error:
```
$ ls Gemfile.lock
Gemfile.lock
$ pdk --version
/opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'bundler' (2.1.4) required by your <cwd>/Gemfile.lock. (Gem::MissingSpecVersionError)
```

**To Reproduce**
Run `pdk` from within a directory that contains a ruby gem (that has a Gemfile.lock). Alternatively, I think the lines from Gemfile.lock that cause the error are:
```
BUNDLED WITH
   2.1.4
```
so maybe it's enough to create a directory with a Gemfile.lock file in it with just these two lines.

**Expected behavior**
Expected `pdk` to run normally, i.e.:
```
$ pdk --version
1.17.0
```

**Additional context**
- PDK installed using macOS package
- Your PDK version: 1.17.0
- Your operating system / platform: macOS 10.14.6
- workaround: explicitly setting BUNDLER_VERSION to a version that's used by PDK results in a working command:
```
$ BUNDLER_VERSION='1.17.2' pdk --version
1.17.0
```

**Comment by logicminds** [comment]
As a work around you can just delete the Gemfile.lock file.  The next run of either bundle install or pdk command will recreated it correctly.  This usually happens when a non pdk process runs bundle install.
