### ISSUE TITLE
[Info] Remove .sync.yml from module build.

### ISSUE THREAD

**Issue by surajbora1** [puppetlabs/pdk#884]
I am using pdk 1.18.0, to remove unwanted files I have created .sync.yml with all configuration details.
**Info**:
When I have executed pdk build command, this file is included in final package *.tar.gz.
Can you please let me know if this is expected behaviour? if yes, please let me know best way to remove this from final module.

**Comment by DavidS** [comment]
Add any files you don't want in the final package in the `.pdkignore`: https://github.com/puppetlabs/pdk-templates#pdkignore
