### ISSUE TITLE
[docs] Workflow graph is likely wrong

### ISSUE THREAD

**Issue by bittner** [puppetlabs/pdk#888]
**Describe the bug**
There is a "PDK development workflow" info graphic in the [PDK documentation](https://puppet.com/docs/pdk/1.x/pdk_overview.html#pdk-development-workflow), which depicts the PDK commands and suggests an order, a flow of tasks, to apply them.

The "Add your own code" and "Test & Iterate" boxes are outside of the grayish background "pdk commands" box. This is likely not fully correct, since "Test & Iterate" entails running `pdk validate` and `pdk test unit`.

**To Reproduce**
1. Go to https://puppet.com/docs/pdk/1.x/pdk_overview.html#pdk-development-workflow
1. Look at the "PDK development workflow" info graphic

**Expected behavior**
The info graph should show the following order / workflow instead:

```
                                                                       |
                      +----------------------+                         |
+----------------+    | pdk new class        |    +---------------+    |     +----------+
| pdk new module | -> | pdk new defined_type | -> | pdk validate  | ---|---> | Add your |
+----------------+    | pdf new task         | <- | pdk test unit |    |     | own code |
                  ->  +----------------------+    +---------------+    |     +----------+
+-------------+  /                                       ^             |           |
| pdk convert | /                                        +-------------|-----------+
+-------------+                                                        |
```
The "Add your own code" box should be the only one outside of the grayish background "pdk commands" box.

**Additional context**
This is all about the content of the Puppet.com website.

**Comment by bittner** [comment]
Could maybe someone from the Puppet website team take a look at this issue?

**Comment by chelnak** [comment]
@bittner we can take a look at this for you!

**Comment by bittner** [comment]
Great! Took almost 3 years, but, yeah, never lose hope. :crossed_fingers: 

I hope the workflow is still correct. I'm only starting to use Puppet again, so not yet up-to-date with the latest advancements at Puppet.

**Comment by david22swan** [comment]
Looks like this has been updated: https://www.puppet.com/docs/pdk/3.x/pdk_overview.html#pdk-development-workflow
