### ISSUE TITLE
(PDK-1655) pdk test unit fails when compiling spec tests on puppet 6.17 due to removal of default_env

### ISSUE THREAD

**Issue by KeithWard** [puppetlabs/pdk#890]
**Describe the bug**
It looks like a change in Puppet 6.17 has resulted in pdk being unable to run rspec tests, as rspec-puppet uses default_env which has been removed in commit https://github.com/puppetlabs/puppet/commit/94df3c1a3992d89b2d7d5db8a70373c135bdd86b
This results in the following crash:
> Failure/Error: require 'puppetlabs_spec_helper/module_spec_helper'
> 
> NameError:
>   undefined local variable or method `default_env' for Puppet::Util:Module
> 

I've raised this upstream in rspec-puppet https://github.com/rodjek/rspec-puppet/issues/796, but raising it here as well for referencing purposes.

**To Reproduce**
Run pdk tests with pdk test unit:

`PDK_PUPPET_VERSION=6.17.0 pdk test unit`

**Expected behaviour**
Tests should run.

**Additional context**
- PDK Installation method: System RPM
- PDK Version: 1.17.0
- Fedora 32

**Comment by nmaludy** [comment]
+1 same problem here

**Comment by alexjfisher** [comment]
Puppet 5 testing also broken in 5.5.21 (also released today)

**Comment by joshcooper** [comment]
There's a PR to rspec-puppet to address this: https://github.com/rodjek/rspec-puppet/pull/797
