### ISSUE TITLE
Allow release command to publish bolt modules

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk#911]
With more and more bolt based modules being published everyday the pdk needs to support developing and release bolt based projects better.

Currently when trying to publish a bolt project to the forge the following error occurs because a manifests directory is not present or some other expectation is not met since this is a bolt based project.

```
Metadata will be generated based on this information, continue? Yes
pdk (ERROR): The module is not Forge compatible
```

The example module that produced this error. 
https://forge.puppet.com/nwops/container_inventory

Manually published by uploading tar.gz file

**Comment by binford2k** [comment]
@logicminds can you add an `issues_url` to your `metadata.json` and try again?

**Comment by logicminds** [comment]
Is this the problem?  If so pdk publish allows this to be optional when it should be required.

**Comment by binford2k** [comment]
I'm pretty sure this is what's causing your failure. https://github.com/puppetlabs/pdk/blob/226a101f3afec06ded291080e8c50f550762618a/lib/pdk/module/metadata.rb#L160-L163
