### ISSUE TITLE
PDK does not support ruby 2.7

### ISSUE THREAD

**Issue by jas01** [puppetlabs/pdk#914]
**Describe the bug**
When I launch pdk new module it's failed with this message

```Metadata will be generated based on this information, continue? Yes
pdk (INFO): Using the default template-url and template-ref.
[✖] Resolving default Gemfile dependencies.
pdk (FATAL): 
/usr/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
        from /usr/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
	from /usr/bin/bundle:23:in `<main>'

pdk (FATAL): Unable to resolve default Gemfile dependencies.
```

After that I must say the most files of the module are still created.

I already try to remove all local gems (arch linux install gem locally on the user space), try to remove ~/.pdk 
All my gems are up2date (of course after removing all gems I re-installed them)

**To Reproduce**
Just do a pdk new module, it's 100% reproductible.

**Additional context**
- Linux: Arch Linux
- Ruby version: 2.7.1 (ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux])
- PDK : Install with gem
- PDK version: 1.18.1

Just to be clear I got this message since I upgrade to ruby 2.7.0, I didn't report the bug because I taught my arch linux are little too up2date. But currently it's 2.7.1 so...

**Comment by DavidS** [comment]
This is fixed in the latest nightlies and will be released as PDK2.0 soon.

```
david@zion:/tmp/test$ pdk validate
pdk (INFO): Using Ruby 2.7.2
pdk (INFO): Using Puppet 7.3.0
pdk (INFO): Running all available validators...
pdk (INFO): Validator 'puppet-syntax' skipped for '/tmp/test'. No files matching '["**/*.pp"]' found to validate.
pdk (INFO): Validator 'puppet-lint' skipped for '/tmp/test'. No files matching '["**/*.pp"]' found to validate.
pdk (INFO): Validator 'puppet-epp' skipped for '/tmp/test'. No files matching '["**/*.epp"]' found to validate.
pdk (INFO): Validator 'task-metadata-lint' skipped for '/tmp/test'. No files matching '["tasks/*.json"]' found to validate.
┌ [✔] Running metadata validators ...
├── [✔] Checking metadata syntax (metadata.json tasks/*.json).
```

**Comment by anders-larsson** [comment]
Hello,

I hope it is OK to revive this issue. We're trying to run pdk in an Alpine Linux v3.13.5 container with ruby version 2.7.3 and PDK version 2.1.0 and we're getting the same error as the original poster of the issue.  PDK was installed as a ruby gem.

Does anyone have any suggestion why it might be failing? Thanks!

```
pdk validate
pdk (WARN): This module is compatible with an older version of PDK. Run `pdk update` to update it to your version of PDK.
pdk (INFO): Using Ruby 2.7.3
pdk (INFO): Using Puppet 6.22.1
pdk (INFO): Running all available validators...
[✖] Resolving default Gemfile dependencies.
pdk (FATAL):
/usr/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
        from /usr/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
        from /usr/bin/bundle:23:in `<main>'

pdk (FATAL): Unable to resolve default Gemfile dependencies.
```
