### ISSUE TITLE
pdk release fails to build without token

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk#917]
**Describe the bug**
The pdk release command does not perform a release because the token for the forge was not entered.  There was not a chance for the token to be entered because I answered 'N' to publishing to the forge.  So even If I did have the token it would never be used.

**To Reproduce**
```
[Q 1/6] Do you want to run the module validation ?
--> Yes

[Q 2/6] Do you want to run the automatic changelog generation ?
--> Yes

[Q 3/6] Do you want to set the module version ?
--> no

[Q 4/6] Do you want to run the dependency-checker on this module?
--> no

[Q 5/6] Do you want to update the documentation for this module?
--> no

[Q 6/6] Do you want to publish the module on the Puppet Forge?
--> no

pdk (ERROR): Missing forge-token option
```

**Expected behavior**
That it would finish the command without error or at least a different error.

**Additional context**
PDK 1.18.1

**Comment by sanfrancrisko** [comment]
@logicminds After some further testing, we realised that this issue wasn't resolved in `2.1.1`. There's a fix going in to the next release (`2.2.0`) - apologies for the incomplete fix
