### ISSUE TITLE
pdk validate does not flag metadata files with invalid JSON escape sequence

### ISSUE THREAD

**Issue by timidri** [puppetlabs/pdk#925]
**Describe the bug**
When a task metadata json file contains an invalid escape sequence, JSON linters (such as jq and Puppet Forge) raise an error but `pdk validate` does not flag that issue.

**To Reproduce**
Consider this task metadata `test.json`:
```
{
  "puppet_task_version": 1,
  "supports_noop": false,
  "description": "A description with an invalid \( escape sequence",
  "parameters": {
  }
}
```
`pdk validate task` passes normally but `jq` flags a problem: 
```
cat test.json | jq
parse error: Invalid escape at line 4, column 67
```

**Expected behavior**
`pdk validate` raises the same error as `jq`.

**Additional context**
- Installation method: native packages
- PDK version `1.18.1`
- OS: MacOS Catalina / Ubuntu 18.04

**Comment by sanfrancrisko** [comment]
Still an issue in PDK 2.1

**Comment by sanfrancrisko** [comment]
Hi @timidri - the underlying gem where this would need to be fixed is `metadata-json-lint`. Would you be able to [raise an issue](https://github.com/voxpupuli/metadata-json-lint/issues) with them to address?

**Comment by timidri** [comment]
@sanfrancrisko Raised issue https://github.com/voxpupuli/metadata-json-lint/issues/119
