### ISSUE TITLE
PDK on Windows can run into a command line length limitation

### ISSUE THREAD

**Issue by bwilcox** [puppetlabs/pdk#955]
**Describe the bug**
This is an edge case.  I have a module that has over 300 classes so far and we just ran into an issue where `pdk validate` starts throwing an error that looks like the following:

```
pdk (FATAL): Failed to execute 'C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/bin/ruby.exe -W0 <module_path>/bin/puppet parser validate --config NUL --modulepath <module_temp_path> <space separated list of all of the classes to validate>': The parameter is incorrect. (87)
```

It looks like I've bumped into a command line length limitation in Windows:  https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation

**To Reproduce**
Create a module with enough classes to exceed the command line limit.

**Expected behavior**
Expect validation to work normally.

**Additional context**
- pdk version: 1.18.1
- OS: Windows 10

It is possible to work around this issue by being specific with the parts of the module I want to validate:

```
pdk validate puppet <sub-directory in manifests to validate>
```

**Comment by sanfrancrisko** [comment]
@bwilcox I tried to reproduce this on a Windows 10 host using PDK 2.1. I basically generated a new module and created 300 classes (see [here](https://github.com/sanfrancrisko/gh955repro)).

As far as I can see, that should reproduce the issue. The accumulated class names list in that repo should be 9000+ characters.

I can't see any code changes between `1.18` and `2.1` that would have mitigated this issue and it should be calling `puppet validate ......` the same way it always has, triggering this issue.

(cc: @jpogran as he had some thoughts on this)
