### ISSUE TITLE
Create Github Workflow for Static & Spec Tests

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/pdk#958]
Create a Github Workflow for the PR Tests that will cover:

**On a hosted runner:**
- For each Ruby version (`2.5`, `2.7`):
  - `rubocop`
  - `spec:coverage`
  - `license_finder`
  - `test_pdk_as_library`
  - `spec`

**Comment by jpogran** [comment]
We should target `windows-latest` and `ubuntu-latest` in hosted as a early warning system.

For acceptance testing, there is little difference (for our purposes) between 2016 and 2019, so we can limit to just that version and simplify things. For bonus points we could add a recent Windows 10 to test a desktop scenario, but I'm not sure what GCP images we have available.

I'm less certain about linux, I will check analytics but I think our most popular there is RHEL. I think ubuntu 20.04 should be good for the moment, and we should add as we get more info.

**Comment by sanfrancrisko** [comment]
Sounds good. We'll go for parity with what we have at the moment, by the sounds of it.

I'll also update the description to plug in to Honeycomb with metrics.

Regarding Windows 10 (or any desktop Windows flavour), it seems to be missing from GCP's list of available images. The provision_service will be gaining support for AWS and Azure at some stage in the future, so I suspect the path of least resistance is to wait until that implementation and then add it in for ourselves.

**Comment by jpogran** [comment]
Updated ticket description with target implementation

**Comment by sanfrancrisko** [comment]
An additional piece of work spurred from this was to refactor the [validator](https://github.com/puppetlabs/provision_service/blob/11f5b7691b03fa9c4a131641e68cead9a5296d1b/backend/lib/utilities/validator.rb) in the [`provision_service`](https://github.com/puppetlabs/provision_service) to allow the `pdk` repo to provision resources in GCP.

See: https://github.com/puppetlabs/provision_service/pull/280

**Comment by sanfrancrisko** [comment]
Given the complexities discovered during implementation for the Acceptance Test workflows, I'll raise separate tickets to cover:

- Acceptance tests on Linux (Hosted Runner on Github)
- Acceptance tests on Windows (GCP provisioned image via [provision_service](https://github.com/puppetlabs/provision_service) - see https://github.com/puppetlabs/provision_service/pull/283)
