### ISSUE TITLE
Documentation issue for brew installs on Mac

### ISSUE THREAD

**Issue by moedes** [puppetlabs/pdk#963]
**Describe the bug**
A documentation error in the PDK documentation around the installation of the PDK.     

**To Reproduce**
Review the documentation at https://puppet.com/docs/pdk/2.x/pdk_install.html#install-pdk-on-macos.  In step 1.,  it shows to install using brew with the command 'brew cask install puppetlabs/puppet/pdk'.   Running this command fails on new releases of HomeBrew.

**Expected behavior**
The documentation needs to be changed to 'brew install --cask puppetlabs/puppet/pdk' as this works to install the cask for the PDK.

**Additional context**
Homebrew is forcing upgrades to the new versions of brew which forces the new behavior

**Comment by hestonhoffman** [comment]
It looks like this is already live in the docs. We just need to run the docs build again to update the site

**Comment by jpogran** [comment]
@hestonhoffman did this get built again? Or will this go out with the upcoming 2.1 release?

**Comment by hestonhoffman** [comment]
@jpogran It will go out with the next release.
