### ISSUE TITLE
github_changelog_generator gem inclusion

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdk#964]
This PR just changed the error message slightly, but as a user, still isn't very helpful. The `Do you want to run the automatic changelog generation?` question is a standard part of `pdk release prep`, so why not include the gem in PDK by default, and provide some documentation on how to use this?

Initially running `pdk release prep` I got `pdk (ERROR): Unable to generate the changelog as the github_changelog_generator gem is not included in this module's Gemfile`. So I did `pdk bundle add github_changelog_generator`. Next run of `pdk release prep` I got
```
/home/kenyon/.pdk/cache/ruby/2.7.0/gems/github_changelog_generator-1.15.2
rake aborted!
Set CHANGELOG_GITHUB_TOKEN environment variable eg 'export CHANGELOG_GITHUB_TOKEN=valid_token_here'
/home/kenyon/git/puppet-bind/Rakefile:48:in `block in <top (required)>'
/home/kenyon/.pdk/cache/ruby/2.7.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/task.rb:42:in `define'
/home/kenyon/.pdk/cache/ruby/2.7.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/task.rb:36:in `initialize'
/home/kenyon/git/puppet-bind/Rakefile:47:in `new'
/home/kenyon/git/puppet-bind/Rakefile:47:in `<top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/opt/puppetlabs/pdk/private/ruby/2.7.2/bin/bundle:23:in `load'
/opt/puppetlabs/pdk/private/ruby/2.7.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
pdk (ERROR): Error generating changelog:
```
:shrug:

_Originally posted by @kenyon in https://github.com/puppetlabs/pdk/issues/907#issuecomment-798829528_

**Comment by sanfrancrisko** [comment]
This ticket will not be addressed in it's current form, but the issue will be considered in the future roadmap of the new PDK: https://puppet.com/blog/the-future-of-the-puppet-developer-kit-pdk/
